import type {
  PlumbingElevationMode,
  PlumbingMaterial,
  PlumbingPipeSchedule,
  PlumbingRunSystem,
} from './plumbingTypes';

export type PlumbingFittingType =
  | 'elbow_90'
  | 'elbow_90_long_sweep'
  | 'elbow_45'
  | 'elbow_22_5'
  | 'elbow_11_25'
  | 'street_elbow_90'
  | 'street_elbow_45'
  | 'offset_bend'
  | 'tee'
  | 'reducing_tee'
  | 'sanitary_tee'
  | 'double_sanitary_tee'
  | 'wye'
  | 'double_wye'
  | 'combo_wye_45'
  | 'cross'
  | 'coupling'
  | 'repair_coupling'
  | 'reducing_coupling'
  | 'transition_coupling'
  | 'union'
  | 'male_adapter'
  | 'female_adapter'
  | 'trap_adapter'
  | 'bushing'
  | 'reducer'
  | 'increaser'
  | 'cap'
  | 'plug'
  | 'cleanout_adapter'
  | 'cleanout_plug'
  | 'p_trap'
  | 'trap_arm'
  | 'closet_bend'
  | 'closet_flange'
  | 'floor_drain_body'
  | 'tub_drain'
  | 'test_tee'
  | 'cleanout_tee'
  | 'floor_cleanout'
  | 'yard_cleanout'
  | 'vent_tee'
  | 'vent_90'
  | 'roof_vent_boot'
  | 'vent_cap'
  | 'drop_ear_elbow'
  | 'stub_out_elbow'
  | 'manifold'
  | 'water_hammer_arrestor'
  | 'hose_bib_adapter'
  | 'ball_valve'
  | 'gate_valve'
  | 'check_valve'
  | 'stop_valve'
  | 'angle_stop'
  | 'pressure_reducing_valve'
  | 'pipe_sleeve'
  | 'footing_sleeve'
  | 'wall_sleeve';

export type PlumbingFittingSystem = PlumbingRunSystem | 'multi';

export type PlumbingFittingUse =
  | 'direction_change'
  | 'branch'
  | 'coupling'
  | 'transition'
  | 'cleanout'
  | 'trap'
  | 'fixture_connection'
  | 'valve'
  | 'sleeve'
  | 'vent_terminal'
  | 'end';

export type PlumbingFitting = {
  id: string;
  type: PlumbingFittingType;
  system: PlumbingFittingSystem;
  nodeId: string;
  connectedRunIds: string[];
  diameterInches: number | null;
  secondaryDiameterInches?: number | null;
  material: PlumbingMaterial;
  schedule?: PlumbingPipeSchedule;
  rotationRad: number;
  elevationMode: PlumbingElevationMode;
  labelVisible: boolean;
  isAutoGenerated: boolean;
};
