import type { SepticTankModel } from './septic/septicTypes';
import type { PlumbingFitting } from './plumbingFittingTypes';

export type PlumbingCodeProfileId =
  | 'conceptual'
  | 'guam_ipc_2009'
  | 'ipc_2024'
  | 'upc_placeholder'
  | 'custom';

export type PlumbingRunSystem =
  | 'cold_water'
  | 'hot_water'
  | 'sanitary'
  | 'vent';

export type PlumbingToolMode =
  | 'select'
  | 'fixture'
  | 'drain'
  | 'vent'
  | 'cold_water'
  | 'hot_water'
  | 'cleanout'
  | 'valve'
  | 'stack'
  | 'connect_fixture'
  | 'label'
  | 'validate';

export type PlumbingFixtureType =
  | 'toilet'
  | 'lavatory'
  | 'shower'
  | 'tub'
  | 'kitchen_sink'
  | 'laundry_box'
  | 'floor_drain'
  | 'hose_bib'
  | 'utility_sink'
  | 'water_heater';

export type PlumbingNodeKind =
  | 'fixture_connection'
  | 'equipment_connection'
  | 'run_tap'
  | 'riser_bottom'
  | 'riser_top'
  | 'fitting'
  | 'wye'
  | 'stack'
  | 'building_drain_exit'
  | 'main_service'
  | 'distribution_box'
  | 'cleanout'
  | 'valve'
  | 'septic_inlet'
  | 'septic_outlet'
  | 'septic_access';

export type PlumbingMaterial =
  | 'pvc'
  | 'abs'
  | 'pex'
  | 'cpvc'
  | 'copper'
  | 'cast_iron'
  | 'other';

export type PlumbingPipeSchedule =
  | 'SCH 40'
  | 'SCH 80'
  | 'N/A';

export type PipeStockLengthPreset =
  | '2ft'
  | '5ft'
  | '10ft'
  | '20ft'
  | '10ft_stick'
  | '20ft_stick'
  | '100ft_coil'
  | '300ft_coil'
  | '500ft_coil'
  | '1000ft_coil'
  | 'custom';

export type PipeStockLengthKind = 'stick' | 'coil' | 'custom';

export type PlumbingElevationMode =
  | 'under_slab'
  | 'in_wall'
  | 'overhead'
  | 'vertical'
  | 'user_defined';

export type PlumbingPoint3D = {
  x: number;
  y: number;
  z: number;
};

export type PlumbingFixtureConnection = {
  id: string;
  system: PlumbingRunSystem;
  label: string;
  defaultDiameterInches: number | null;
  offset: PlumbingPoint3D;
};

export type PlumbingFixture = {
  id: string;
  fixtureType: PlumbingFixtureType;
  mark: string;
  displayName: string;
  position: PlumbingPoint3D;
  rotationRadians: number;
  connectionNodeIds: Partial<Record<PlumbingRunSystem, string[]>>;
  notes?: string;
};

export type PlumbingNode = {
  id: string;
  kind: PlumbingNodeKind;
  system: PlumbingRunSystem;
  position: PlumbingPoint3D;
  fixtureId?: string;
  equipmentId?: string;
  septicTankId?: string;
  label: string;
};

export type PlumbingRun = {
  id: string;
  system: PlumbingRunSystem;
  startNodeId: string;
  endNodeId: string;
  path: PlumbingPoint3D[];
  diameterInches: number | null;
  material: PlumbingMaterial;
  schedule?: PlumbingPipeSchedule;
  stockLengthFt: number;
  stockLengthPreset: PipeStockLengthPreset;
  stockLengthKind: PipeStockLengthKind;
  slopeInPerFt?: number;
  elevationMode: PlumbingElevationMode;
  labelVisible: boolean;
};

export type PlumbingEquipmentType =
  | 'cleanout'
  | 'shutoff_valve'
  | 'waste_stack'
  | 'vent_stack'
  | 'combined_stack'
  | 'roof_vent_termination'
  | 'meter'
  | 'main_service_point'
  | 'distribution_box'
  | 'building_drain_exit';

export type PlumbingEquipment = {
  id: string;
  equipmentType: PlumbingEquipmentType;
  label: string;
  position: PlumbingPoint3D;
  rotationRadians: number;
  connectionNodeIds: string[];
};

export type PlumbingRoughInSystem =
  | 'sanitary'
  | 'vent'
  | 'cold_water'
  | 'hot_water';

export type PlumbingRiserKind =
  | 'vertical_stub_up'
  | 'vertical_drop'
  | 'in_wall_riser'
  | 'fixture_tailpiece'
  | 'trap_arm'
  | 'closet_bend_connection';

export type PlumbingFixtureRoughInAssembly = {
  id: string;
  fixtureId: string;
  system: PlumbingRoughInSystem;
  mainRunId?: string;
  tapNodeId?: string;
  fixtureNodeId: string;
  riserBottomNodeId: string;
  riserTopNodeId: string;
  branchRunId?: string;
  riserRunId: string;
  trapArmRunId?: string;
  fittingIds: string[];
  diameterInches: number | null;
  material: PlumbingMaterial;
  schedule?: PlumbingPipeSchedule;
  elevationMode: PlumbingElevationMode;
  riserKind: PlumbingRiserKind;
  labelVisible: boolean;
  isAutoGenerated: boolean;
};

export type PlumbingSettings = {
  codeProfileId: PlumbingCodeProfileId;
  defaultWaterMaterial: PlumbingMaterial;
  defaultWasteVentMaterial: PlumbingMaterial;
  fixtureMarkCounters: Partial<Record<PlumbingFixtureType, number>>;
};

export type PlumbingSystem = {
  schemaVersion: number;
  codeProfileId: PlumbingCodeProfileId;
  fixtures: PlumbingFixture[];
  nodes: PlumbingNode[];
  runs: PlumbingRun[];
  fittings: PlumbingFitting[];
  roughIns: PlumbingFixtureRoughInAssembly[];
  equipment: PlumbingEquipment[];
  septicTanks: SepticTankModel[];
  settings: PlumbingSettings;
};

export type PlumbingSelection =
  | { kind: 'fixture'; id: string }
  | { kind: 'run'; id: string }
  | { kind: 'run-route-point'; runId: string; pointIndex: number }
  | { kind: 'fitting'; id: string }
  | { kind: 'rough-in'; id: string }
  | { kind: 'node'; id: string }
  | { kind: 'equipment'; id: string }
  | { kind: 'septic-tank'; id: string }
  | { kind: 'none' };

export type PlumbingRunDraft = {
  system: PlumbingRunSystem;
  startNodeId: string;
  roughInMainRunId?: string;
  roughInTapPoint?: PlumbingPoint3D;
  roughInSegmentIndex?: number;
  routePoints: PlumbingPoint3D[];
  previewPoint?: PlumbingPoint3D;
  previewSnap?:
    | { kind: 'node'; nodeId: string }
    | { kind: 'run-segment'; runId: string; segmentIndex: number; point: PlumbingPoint3D };
};

export type PlumbingValidationSeverity = 'error' | 'warning' | 'info';

export type PlumbingValidationIssue = {
  id: string;
  severity: PlumbingValidationSeverity;
  code:
    | 'fixture_missing_required_node'
    | 'fixture_missing_required_run'
    | 'run_missing_diameter'
    | 'sanitary_run_missing_slope'
    | 'run_missing_start_node'
    | 'run_missing_end_node'
    | 'sanitary_disconnected'
    | 'vent_disconnected'
    | 'duplicate_fixture_mark'
    | 'orphan_node'
    | 'pipe_crosses_foundation'
    | 'pipe_crosses_rc_column'
    | 'run_missing_stock_length'
    | 'invalid_stock_length'
    | 'invalid_fitting_for_system'
    | 'invalid_fitting_for_material'
    | 'fitting_missing_diameter'
    | 'fitting_diameter_mismatch'
    | 'fitting_missing_schedule'
    | 'fixture_missing_required_rough_in'
    | 'rough_in_missing_fixture'
    | 'rough_in_missing_fixture_node'
    | 'rough_in_missing_top_node'
    | 'rough_in_missing_bottom_node'
    | 'rough_in_invalid_riser_height'
    | 'rough_in_disconnected_sanitary'
    | 'rough_in_missing_takeoff_mapping'
    | 'wc_missing_closet_flange'
    | 'wc_missing_closet_bend'
    | 'fixture_missing_trap'
    | 'branch_missing_tap_fitting'
    | 'pipe_crosses_foundation_with_sleeve'
    | 'sanitary_run_slopes_wrong_direction'
    | 'under_slab_pipe_above_slab'
    | 'pipe_below_grade_missing_elevation_mode'
    | 'vent_does_not_rise_through_roof'
    | 'user_defined_run_missing_elevation'
    | 'sharp_bend_missing_fitting'
    | 'pipe_crosses_footing_without_sleeve'
    | 'fixture_missing_procedural_renderer'
    | 'fitting_type_missing_procedural_renderer'
    | 'septic_tank_too_close_to_building'
    | 'sanitary_drain_path_missing_septic'
    | 'sanitary_drain_path_slope_below_ipc'
    | 'pipe_crosses_plinth_beam'
    | 'distribution_box_missing_drain_inlet'
    | 'distribution_box_missing_septic_outlet'
    | 'septic_missing_distribution_box'
    | 'septic_direct_connection_without_distribution_box'
    | 'septic_multiple_inlet_lines'
    | 'manual_fitting_not_on_solved_route'
    | 'solved_pipe_endpoint_missing'
    | 'solved_coupler_min_stub_violation'
    | 'solved_coupling_not_contiguous'
    | 'solved_dbox_inlet_not_port_aligned'
    | 'distribution_box_outlet_missing_solved_port'
    | 'distribution_box_outlet_pipe_not_port_aligned'
    | 'distribution_box_outlet_stub_missing'
    | 'distribution_box_outlet_to_septic_gap'
    | 'distribution_box_outlet_pipe_enters_body'
    | 'septic_inlet_pipe_not_port_aligned'
    | 'septic_inlet_pipe_misses_port'
    | 'septic_inlet_connection_requires_dbox_reposition'
    | 'dbox_outlet_not_aligned_to_septic_inlet'
    | 'dbox_auto_repositioned_for_septic_inlet';
  message: string;
  objectKind: 'fixture' | 'run' | 'node' | 'fitting' | 'rough-in' | 'equipment' | 'foundation' | 'septic-tank' | 'system';
  objectId?: string;
};

export type PlumbingLegendItem = {
  key: string;
  label: string;
  system?: PlumbingRunSystem;
  component?: 'cleanout' | 'valve' | 'stack';
};

export type PlumbingFixtureScheduleRow = {
  fixtureId: string;
  mark: string;
  fixtureType: PlumbingFixtureType;
  displayName: string;
  coldWater: boolean;
  hotWater: boolean;
  sanitary: boolean;
  vent: boolean;
  xMeters: number;
  zMeters: number;
};
