import type { ReactNode } from 'react';
import type { DocumentCompany, DocumentProject } from './professionalDocumentTypes';
import DocumentStatusBadge from './DocumentStatusBadge';

interface ProfessionalDocumentShellProps {
  documentTitle: string;
  documentTypeLabel: string;
  documentNumber?: string;
  status?: string;
  generatedDate?: string;
  company?: DocumentCompany;
  project?: DocumentProject;
  children: ReactNode;
  footerText?: string;
  /** Applied to the outermost wrapper only — use for margin adjustments. */
  className?: string;
}

/**
 * White-paper wrapper for professional document previews.
 *
 * The paper surface always renders as white with dark text regardless of the
 * surrounding app theme — identical to the Change Order document pattern.
 * No `dark:` Tailwind variants are used inside the document body.
 */
export default function ProfessionalDocumentShell({
  documentTitle,
  documentTypeLabel,
  documentNumber,
  status,
  generatedDate,
  company,
  project,
  children,
  footerText,
  className,
}: ProfessionalDocumentShellProps) {
  return (
    <div
      className={[
        'min-w-0 max-w-full overflow-x-hidden bg-white p-6 text-slate-950',
        'print:bg-white print:text-black',
        className ?? '',
      ]
        .filter(Boolean)
        .join(' ')}
    >
      {/* ── Header ─────────────────────────────────────────────────────── */}
      <header className="border-b border-slate-200 pb-6">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
          {/* Company block */}
          <div className="min-w-0 flex-1">
            {company?.logoUrl ? (
              <img
                src={company.logoUrl}
                alt=""
                className="mb-3 max-h-14 max-w-[200px] object-contain"
              />
            ) : null}
            <p className="text-lg font-bold text-slate-900">
              {company?.name ?? 'Contractor'}
            </p>
            {company?.address ? (
              <p className="mt-1 whitespace-pre-wrap text-sm text-slate-600">
                {company.address}
              </p>
            ) : null}
            <div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-sm text-slate-600">
              {company?.phone ? <span>{company.phone}</span> : null}
              {company?.email ? <span>{company.email}</span> : null}
              {company?.licenseNumber ? (
                <span>License {company.licenseNumber}</span>
              ) : null}
            </div>
          </div>

          {/* Document-type meta box */}
          <div className="shrink-0 rounded-lg border border-slate-300 bg-slate-50 px-4 py-3 text-right">
            <p className="text-xs font-bold uppercase tracking-widest text-slate-700">
              {documentTypeLabel}
            </p>
            {documentNumber ? (
              <p className="mt-1 text-sm font-semibold text-slate-900">{documentNumber}</p>
            ) : null}
            {generatedDate ? (
              <p className="mt-1 text-xs text-slate-600">Date: {generatedDate}</p>
            ) : null}
            {status ? (
              <div className="mt-2 flex justify-end">
                <DocumentStatusBadge status={status} />
              </div>
            ) : null}
          </div>
        </div>

        {/* Document title */}
        <h1 className="mt-4 break-words text-xl font-bold text-slate-900 [overflow-wrap:anywhere]">
          {documentTitle}
        </h1>

        {/* Project sub-line */}
        {project?.name ? (
          <p className="mt-1 text-sm text-slate-600">
            {project.name}
            {project.projectNumber ? ` · #${project.projectNumber}` : ''}
            {project.address ? ` · ${project.address}` : ''}
          </p>
        ) : null}
      </header>

      {/* ── Body ───────────────────────────────────────────────────────── */}
      <div className="mt-6 space-y-6">{children}</div>

      {/* ── Footer ─────────────────────────────────────────────────────── */}
      <footer className="mt-8 border-t border-slate-200 pt-4 text-xs text-slate-500">
        Generated by Concrete Calc
        {footerText ? ` · ${footerText}` : ''}
      </footer>
    </div>
  );
}
