import type { DocumentQuestion } from '../../types';

export const STATUS_OPTIONS = [
  { value: 'draft', label: 'Draft' },
  { value: 'open', label: 'Open' },
  { value: 'passed', label: 'Passed' },
  { value: 'passed_with_notes', label: 'Passed with Notes' },
  { value: 'failed', label: 'Failed' },
  { value: 'corrective_action_required', label: 'Corrective Action Required' },
  { value: 'reinspection_required', label: 'Reinspection Required' },
  { value: 'closed', label: 'Closed' },
];

export const INSPECTION_TYPE_OPTIONS = [
  { value: 'pre_placement', label: 'Pre-placement Inspection' },
  { value: 'concrete_placement', label: 'Concrete Placement Inspection' },
  { value: 'reinforcement', label: 'Reinforcement Inspection' },
  { value: 'formwork', label: 'Formwork Inspection' },
  { value: 'anchor_embed', label: 'Anchor Bolt / Embed Inspection' },
  { value: 'slump_air_temp', label: 'Slump / Air / Temperature Test' },
  { value: 'cylinder_break', label: 'Cylinder / Break Test' },
  { value: 'finishing', label: 'Finishing Inspection' },
  { value: 'curing', label: 'Curing Inspection' },
  { value: 'general_qc', label: 'General QC Inspection' },
  { value: 'other', label: 'Other' },
];

/**
 * QC Report Pack question bank for the Document Builder intake form.
 * Answer keys align with `qcReportPreviewAdapter` and `QcReportDocument` renderer.
 */
export const qcReportQuestions: DocumentQuestion[] = [
  // ── Quick mode (field-usable) ───────────────────────────────────────────────
  {
    questionKey: 'reportDate',
    label: 'Report date',
    type: 'date',
    group: 'schedule',
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'reportNumber',
    label: 'Report number',
    type: 'text',
    group: 'schedule',
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'preparedBy',
    label: 'Prepared by',
    type: 'text',
    group: 'parties',
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'inspectionType',
    label: 'Inspection type',
    type: 'select',
    group: 'scope',
    options: INSPECTION_TYPE_OPTIONS,
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'inspectionLocation',
    label: 'Inspection location / area',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'overallStatus',
    label: 'Overall status',
    type: 'select',
    group: 'execution',
    options: STATUS_OPTIONS,
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'summary',
    label: 'Summary',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'status',
    label: 'Status',
    type: 'select',
    group: 'execution',
    options: STATUS_OPTIONS,
    required: false,
    mode: 'quick',
  },

  // ── Standard mode ─────────────────────────────────────────────────────────
  {
    questionKey: 'specificationReference',
    label: 'Specification reference',
    type: 'text',
    group: 'compliance',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'drawingReference',
    label: 'Drawing reference',
    type: 'text',
    group: 'compliance',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'workInspected',
    label: 'Work inspected',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'inspectionMethod',
    label: 'Inspection method',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'acceptanceCriteria',
    label: 'Acceptance criteria',
    type: 'text',
    group: 'compliance',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'observations',
    label: 'Observations',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'deficiencies',
    label: 'Deficiencies',
    type: 'text',
    group: 'risk',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'correctiveActions',
    label: 'Corrective actions',
    type: 'text',
    group: 'change_management',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'responsibleParty',
    label: 'Responsible party',
    type: 'text',
    group: 'parties',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'followUpRequired',
    label: 'Follow-up required',
    type: 'text',
    group: 'change_management',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'followUpDate',
    label: 'Follow-up date',
    type: 'date',
    group: 'schedule',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'qcNotes',
    label: 'QC notes',
    type: 'text',
    group: 'compliance',
    required: false,
    mode: 'standard',
  },

  // ── Advanced mode ─────────────────────────────────────────────────────────
  {
    questionKey: 'testType',
    label: 'Test type',
    type: 'text',
    group: 'compliance',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'testResults',
    label: 'Test results',
    type: 'text',
    group: 'compliance',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'testingAgency',
    label: 'Testing agency',
    type: 'text',
    group: 'parties',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'sampleNumbers',
    label: 'Sample numbers',
    type: 'text',
    group: 'compliance',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'concretePlacementDate',
    label: 'Concrete placement date',
    type: 'date',
    group: 'schedule',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'mixDesignReference',
    label: 'Mix design reference',
    type: 'text',
    group: 'compliance',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'truckTicketNumbers',
    label: 'Truck ticket numbers',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'slump',
    label: 'Slump',
    type: 'text',
    group: 'compliance',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'airContent',
    label: 'Air content',
    type: 'text',
    group: 'compliance',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'concreteTemperature',
    label: 'Concrete temperature',
    type: 'text',
    group: 'compliance',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'ambientTemperature',
    label: 'Ambient temperature',
    type: 'text',
    group: 'compliance',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'cylinderSetNumbers',
    label: 'Cylinder set numbers',
    type: 'text',
    group: 'compliance',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'breakResults',
    label: 'Break results',
    type: 'text',
    group: 'compliance',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'reinspectionRequired',
    label: 'Reinspection required',
    type: 'text',
    group: 'change_management',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'reinspectionDate',
    label: 'Reinspection date',
    type: 'date',
    group: 'schedule',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'inspectorName',
    label: 'Inspector name',
    type: 'text',
    group: 'parties',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'inspectorCompany',
    label: 'Inspector company',
    type: 'text',
    group: 'parties',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'ownerRepresentative',
    label: 'Owner representative',
    type: 'text',
    group: 'parties',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'reviewedBy',
    label: 'Reviewed by',
    type: 'text',
    group: 'parties',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'signatureDate',
    label: 'Signature date',
    type: 'date',
    group: 'schedule',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'photos',
    label: 'Photos',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'advanced',
    helperText: 'Photo references or descriptions',
  },
  {
    questionKey: 'attachments',
    label: 'Attachments',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'attachmentNotes',
    label: 'Attachment notes',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'advanced',
  },
];
