import type { DocumentQuestion } from '../../types';

export const STATUS_OPTIONS = [
  { value: 'draft', label: 'Draft' },
  { value: 'submitted', label: 'Submitted' },
  { value: 'under_review', label: 'Under Review' },
  { value: 'accepted', label: 'Accepted' },
  { value: 'closed', label: 'Closed' },
];

export const WARRANTY_PERIOD_OPTIONS = [
  { value: '30_days', label: '30 Days' },
  { value: '90_days', label: '90 Days' },
  { value: '6_months', label: '6 Months' },
  { value: '1_year', label: '1 Year' },
  { value: '2_years', label: '2 Years' },
  { value: 'manufacturer_only', label: 'Manufacturer Warranty Only' },
  { value: 'no_warranty', label: 'No Warranty' },
  { value: 'custom', label: 'Custom' },
];

export const FINAL_INSPECTION_RESULT_OPTIONS = [
  { value: 'passed', label: 'Passed' },
  { value: 'passed_with_notes', label: 'Passed with Notes' },
  { value: 'punch_list_required', label: 'Punch List Required' },
  { value: 'failed', label: 'Failed' },
  { value: 'not_completed', label: 'Not Completed' },
];

export const PUNCH_LIST_STATUS_OPTIONS = [
  { value: 'none', label: 'None' },
  { value: 'open', label: 'Open' },
  { value: 'in_progress', label: 'In Progress' },
  { value: 'complete', label: 'Complete' },
  { value: 'not_applicable', label: 'Not Applicable' },
];

/**
 * Warranty / Closeout Pack question bank for the Document Builder intake form.
 */
export const warrantyCloseoutQuestions: DocumentQuestion[] = [
  // ── Quick mode ──────────────────────────────────────────────────────────────
  {
    questionKey: 'letterDate',
    label: 'Letter date',
    type: 'text',
    group: 'schedule',
    required: false,
    mode: 'quick',
    helperText: 'e.g. 2026-06-03 or June 3, 2026',
  },
  {
    questionKey: 'documentNumber',
    label: 'Document number',
    type: 'text',
    group: 'schedule',
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'preparedBy',
    label: 'Prepared by',
    type: 'text',
    group: 'parties',
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'recipientName',
    label: 'Recipient name',
    type: 'text',
    group: 'parties',
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'projectCompletionDate',
    label: 'Project completion date',
    type: 'text',
    group: 'schedule',
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'warrantyStartDate',
    label: 'Warranty start date',
    type: 'text',
    group: 'schedule',
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'warrantyPeriod',
    label: 'Warranty period',
    type: 'select',
    group: 'compliance',
    options: WARRANTY_PERIOD_OPTIONS,
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'closeoutSummary',
    label: 'Closeout summary',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'status',
    label: 'Status',
    type: 'select',
    group: 'execution',
    options: STATUS_OPTIONS,
    required: false,
    mode: 'quick',
  },

  // ── Standard mode ─────────────────────────────────────────────────────────
  {
    questionKey: 'projectScopeCompleted',
    label: 'Project scope completed',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'warrantyCoverage',
    label: 'Warranty coverage',
    type: 'text',
    group: 'compliance',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'warrantyExclusions',
    label: 'Warranty exclusions',
    type: 'text',
    group: 'compliance',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'ownerResponsibilities',
    label: 'Owner responsibilities',
    type: 'text',
    group: 'parties',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'maintenanceInstructions',
    label: 'Maintenance instructions',
    type: 'text',
    group: 'compliance',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'closeoutDocumentsIncluded',
    label: 'Other closeout documents included',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'punchListStatus',
    label: 'Punch list status',
    type: 'select',
    group: 'execution',
    options: PUNCH_LIST_STATUS_OPTIONS,
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'finalInspectionDate',
    label: 'Final inspection date',
    type: 'text',
    group: 'schedule',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'finalInspectionResult',
    label: 'Final inspection result',
    type: 'select',
    group: 'execution',
    options: FINAL_INSPECTION_RESULT_OPTIONS,
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'contractorContactName',
    label: 'Contractor contact name',
    type: 'text',
    group: 'parties',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'contractorContactPhone',
    label: 'Contractor contact phone',
    type: 'text',
    group: 'parties',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'contractorContactEmail',
    label: 'Contractor contact email',
    type: 'text',
    group: 'parties',
    required: false,
    mode: 'standard',
  },

  // ── Advanced mode ─────────────────────────────────────────────────────────
  {
    questionKey: 'retainageStatus',
    label: 'Retainage status',
    type: 'text',
    group: 'pricing',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'finalPaymentStatus',
    label: 'Final payment status',
    type: 'text',
    group: 'pricing',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'lienWaiverStatus',
    label: 'Lien waiver status',
    type: 'text',
    group: 'pricing',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'asBuiltDrawingsIncluded',
    label: 'As-built drawings included',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'advanced',
    helperText: 'e.g. Yes, N/A, Pending',
  },
  {
    questionKey: 'operationManualsIncluded',
    label: 'Operation / maintenance manuals included',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'testReportsIncluded',
    label: 'Test reports included',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'materialCertificationsIncluded',
    label: 'Material certifications included',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'keysAccessCodesReturned',
    label: 'Keys / access codes returned',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'spareMaterialsProvided',
    label: 'Spare materials provided',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'unresolvedItems',
    label: 'Unresolved items',
    type: 'text',
    group: 'change_management',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'followUpRequired',
    label: 'Follow-up required',
    type: 'text',
    group: 'change_management',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'followUpDate',
    label: 'Follow-up date',
    type: 'text',
    group: 'schedule',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'attachmentNotes',
    label: 'Attachment notes',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'additionalTerms',
    label: 'Additional terms',
    type: 'text',
    group: 'compliance',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'ownerRepresentative',
    label: 'Owner / client representative',
    type: 'text',
    group: 'parties',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'reviewedBy',
    label: 'Reviewed by (owner)',
    type: 'text',
    group: 'parties',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'signatureDate',
    label: 'Signature date',
    type: 'text',
    group: 'schedule',
    required: false,
    mode: 'advanced',
  },
];
