import type { DocumentQuestion, QuestionOption } from '../../types';

const FAR_STATUS_OPTIONS: QuestionOption[] = [
  { value: 'Draft', label: 'Draft' },
  { value: 'Submitted', label: 'Submitted' },
  { value: 'Under Review', label: 'Under Review' },
  { value: 'Approved', label: 'Approved' },
  { value: 'Rejected', label: 'Rejected' },
  { value: 'Closed', label: 'Closed' },
  { value: 'Void', label: 'Void' },
];

export const farQuestions: DocumentQuestion[] = [
  { questionKey: 'farNumber', label: 'FAR number', type: 'text', group: 'scope', required: false, mode: 'quick' },
  { questionKey: 'title', label: 'Title', type: 'text', group: 'scope', required: true, mode: 'quick' },
  { questionKey: 'requestedBy', label: 'Requested by', type: 'text', group: 'parties', required: false, mode: 'quick' },
  { questionKey: 'submittedTo', label: 'Submitted to', type: 'text', group: 'parties', required: false, mode: 'quick' },
  { questionKey: 'location', label: 'Location', type: 'text', group: 'scope', required: false, mode: 'quick' },
  { questionKey: 'description', label: 'Description', type: 'text', group: 'scope', required: true, mode: 'quick' },
  { questionKey: 'reason', label: 'Reason', type: 'text', group: 'scope', required: false, mode: 'quick' },
  {
    questionKey: 'status',
    label: 'Status',
    type: 'select',
    group: 'execution',
    options: FAR_STATUS_OPTIONS,
    required: false,
    mode: 'quick',
  },
  { questionKey: 'existingCondition', label: 'Existing condition', type: 'text', group: 'scope', required: false, mode: 'standard' },
  { questionKey: 'proposedAdjustment', label: 'Proposed adjustment', type: 'text', group: 'scope', required: false, mode: 'standard' },
  { questionKey: 'laborImpact', label: 'Labor impact', type: 'text', group: 'change_management', required: false, mode: 'standard' },
  { questionKey: 'materialImpact', label: 'Material impact', type: 'text', group: 'change_management', required: false, mode: 'standard' },
  { questionKey: 'equipmentImpact', label: 'Equipment impact', type: 'text', group: 'change_management', required: false, mode: 'standard' },
  { questionKey: 'costImpact', label: 'Cost impact', type: 'text', group: 'change_management', required: false, mode: 'standard' },
  { questionKey: 'scheduleImpact', label: 'Schedule impact', type: 'text', group: 'change_management', required: false, mode: 'standard' },
  { questionKey: 'priority', label: 'Priority', type: 'text', group: 'schedule', required: false, mode: 'standard' },
  { questionKey: 'dueDate', label: 'Due date', type: 'text', group: 'schedule', required: false, mode: 'standard' },
  { questionKey: 'relatedRfi', label: 'Related RFI', type: 'text', group: 'execution', required: false, mode: 'advanced' },
  { questionKey: 'relatedChangeOrder', label: 'Related change order', type: 'text', group: 'execution', required: false, mode: 'advanced' },
  { questionKey: 'drawingReference', label: 'Drawing reference', type: 'text', group: 'execution', required: false, mode: 'advanced' },
  { questionKey: 'specReference', label: 'Spec reference', type: 'text', group: 'execution', required: false, mode: 'advanced' },
  { questionKey: 'fieldPhotos', label: 'Field photos (references)', type: 'text', group: 'execution', required: false, mode: 'advanced' },
  { questionKey: 'contractorRecommendation', label: 'Contractor recommendation', type: 'text', group: 'execution', required: false, mode: 'advanced' },
  { questionKey: 'reviewerResponse', label: 'Reviewer response', type: 'text', group: 'execution', required: false, mode: 'standard' },
  { questionKey: 'reviewedBy', label: 'Reviewed by', type: 'text', group: 'execution', required: false, mode: 'standard' },
  { questionKey: 'responseDate', label: 'Response date', type: 'text', group: 'execution', required: false, mode: 'standard' },
  { questionKey: 'approvalDecision', label: 'Approval decision', type: 'text', group: 'execution', required: false, mode: 'standard' },
];
