import type { DocumentQuestion } from '../../types';

const STATUS_OPTIONS = [
  { value: 'draft', label: 'Draft' },
  { value: 'submitted', label: 'Submitted' },
  { value: 'under_review', label: 'Under Review' },
  { value: 'approved', label: 'Approved' },
  { value: 'approved_as_noted', label: 'Approved as Noted' },
  { value: 'revise_and_resubmit', label: 'Revise and Resubmit' },
  { value: 'rejected', label: 'Rejected' },
  { value: 'closed', label: 'Closed' },
];

const REVIEW_STATUS_OPTIONS = [
  { value: 'pending_review', label: 'Pending Review' },
  { value: 'approved', label: 'Approved' },
  { value: 'approved_as_noted', label: 'Approved as Noted' },
  { value: 'revise_and_resubmit', label: 'Revise and Resubmit' },
  { value: 'rejected', label: 'Rejected' },
  { value: 'no_exception_taken', label: 'No Exception Taken' },
];

/**
 * Submittal Pack question bank for the Document Builder intake form.
 * Answer keys align with `submittalPreviewAdapter` and `SubmittalDocument` renderer.
 */
export const submittalQuestions: DocumentQuestion[] = [
  {
    questionKey: 'submittalNumber',
    label: 'Submittal number',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'submittalTitle',
    label: 'Submittal title',
    type: 'text',
    group: 'scope',
    required: true,
    mode: 'quick',
  },
  {
    questionKey: 'specSection',
    label: 'Spec section',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'status',
    label: 'Status',
    type: 'select',
    group: 'execution',
    options: STATUS_OPTIONS,
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'submittedBy',
    label: 'Submitted by',
    type: 'text',
    group: 'parties',
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'submittedTo',
    label: 'Submitted to',
    type: 'text',
    group: 'parties',
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'submittalDate',
    label: 'Submittal date',
    type: 'date',
    group: 'schedule',
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'productData',
    label: 'Product data',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'shopDrawings',
    label: 'Shop drawings',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'samples',
    label: 'Samples',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'reviewer',
    label: 'Reviewer',
    type: 'text',
    group: 'parties',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'dueDate',
    label: 'Due date',
    type: 'date',
    group: 'schedule',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'manufacturer',
    label: 'Manufacturer',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'supplier',
    label: 'Supplier',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'reviewStatus',
    label: 'Review status',
    type: 'select',
    group: 'execution',
    options: REVIEW_STATUS_OPTIONS,
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'reviewerComments',
    label: 'Reviewer comments',
    type: 'text',
    group: 'execution',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'contractorStatement',
    label: 'Contractor statement',
    type: 'text',
    group: 'execution',
    required: false,
    mode: 'advanced',
    helperText: 'Leave blank to use the standard conformance statement on the cover sheet.',
  },
  {
    questionKey: 'attachments',
    label: 'Other attachments',
    type: 'text',
    group: 'execution',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'certifications',
    label: 'Certifications',
    type: 'text',
    group: 'execution',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'relatedRfi',
    label: 'Related RFI',
    type: 'text',
    group: 'execution',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'relatedChangeOrder',
    label: 'Related change order',
    type: 'text',
    group: 'execution',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'reviewedBy',
    label: 'Reviewed by',
    type: 'text',
    group: 'execution',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'signatureDate',
    label: 'Signature date',
    type: 'date',
    group: 'execution',
    required: false,
    mode: 'advanced',
  },
];
