import type { DocumentQuestion, QuestionOption } from '../../types';

const projectTypeOptions: QuestionOption[] = [
  { value: 'remodel', label: 'Remodel' },
  { value: 'repair', label: 'Repair' },
  { value: 'concrete', label: 'Concrete' },
  { value: 'roofing', label: 'Roofing' },
  { value: 'adu', label: 'ADU' },
  { value: 'deck', label: 'Deck' },
  { value: 'fence', label: 'Fence' },
  { value: 'new_construction', label: 'New Construction' },
  { value: 'insurance_restoration', label: 'Insurance Restoration' },
];

const priceModelOptions: QuestionOption[] = [
  { value: 'fixed_price', label: 'Fixed Price' },
  { value: 'time_and_materials', label: 'Time and Materials' },
  { value: 'cost_plus', label: 'Cost Plus' },
];

/**
 * Generic Residential Pack question bank.
 *
 * Each question declares the lowest `mode` at which it appears (quick is a
 * subset of standard, which is a subset of advanced), its intake `group`,
 * optional visibility/required rules, the clauses/addenda it can pull in, and
 * any risk signals. The engine filters and resolves these declaratively; there
 * is no per-question imperative logic.
 */
export const residentialQuestions: DocumentQuestion[] = [
  // --- Quick (core ~10) ---
  {
    questionKey: 'projectType',
    label: 'Project type',
    type: 'select',
    group: 'project',
    options: projectTypeOptions,
    required: true,
    mode: 'quick',
  },
  {
    questionKey: 'priceModel',
    label: 'Pricing model',
    type: 'select',
    group: 'pricing',
    options: priceModelOptions,
    required: true,
    mode: 'quick',
    drivesClauses: ['pricing.fixed_price', 'pricing.time_and_materials', 'pricing.cost_plus'],
    riskSignals: [
      {
        whenEquals: ['time_and_materials'],
        key: 'pricing.tm',
        label: 'Time and materials pricing shifts cost overrun risk to the owner and invites disputes.',
        points: 15,
      },
      {
        whenEquals: ['cost_plus'],
        key: 'pricing.cost_plus',
        label: 'Cost-plus pricing has no fixed ceiling unless a guaranteed maximum is set.',
        points: 12,
      },
    ],
  },
  {
    questionKey: 'contractorLegalName',
    label: 'Contractor legal name',
    type: 'text',
    group: 'parties',
    required: true,
    mode: 'quick',
  },
  {
    questionKey: 'ownerFullName',
    label: 'Owner full name',
    type: 'text',
    group: 'parties',
    required: true,
    mode: 'quick',
  },
  {
    questionKey: 'propertyAddress',
    label: 'Project property address',
    type: 'text',
    group: 'property',
    required: true,
    mode: 'quick',
  },
  {
    questionKey: 'scopeSummary',
    label: 'Scope of work summary',
    type: 'text',
    group: 'scope',
    required: true,
    mode: 'quick',
  },
  {
    questionKey: 'contractPrice',
    label: 'Fixed contract price',
    type: 'number',
    group: 'pricing',
    required: false,
    mode: 'quick',
    visibleWhen: [{ questionKey: 'priceModel', equals: ['fixed_price'] }],
    requiredWhen: [{ questionKey: 'priceModel', equals: ['fixed_price'] }],
  },
  {
    questionKey: 'startDate',
    label: 'Approximate start date',
    type: 'date',
    group: 'schedule',
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'completionDate',
    label: 'Approximate completion date',
    type: 'date',
    group: 'schedule',
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'depositRequired',
    label: 'Is an upfront deposit required?',
    type: 'boolean',
    group: 'payments',
    required: false,
    mode: 'quick',
    drivesClauses: ['deposit.clause'],
  },

  // --- Standard (~+15) ---
  {
    questionKey: 'exclusionsSummary',
    label: 'Notable exclusions',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'estimatedTotal',
    label: 'Estimated total',
    type: 'number',
    group: 'pricing',
    required: false,
    mode: 'standard',
    visibleWhen: [{ questionKey: 'priceModel', equals: ['time_and_materials', 'cost_plus'] }],
    requiredWhen: [{ questionKey: 'priceModel', equals: ['time_and_materials', 'cost_plus'] }],
  },
  {
    questionKey: 'progressPayments',
    label: 'Use milestone / progress payments?',
    type: 'boolean',
    group: 'payments',
    required: false,
    mode: 'standard',
    drivesClauses: ['payment.progress'],
  },
  {
    questionKey: 'retainage',
    label: 'Hold retainage until substantial completion?',
    type: 'boolean',
    group: 'payments',
    required: false,
    mode: 'standard',
    drivesClauses: ['payment.retainage'],
  },
  {
    questionKey: 'changeOrderProcess',
    label: 'Change order process',
    type: 'select',
    group: 'change_management',
    options: [
      { value: 'written_required', label: 'Written change orders required' },
      { value: 'verbal_ok', label: 'Verbal changes allowed' },
    ],
    required: false,
    mode: 'standard',
    riskSignals: [
      {
        whenEquals: ['verbal_ok'],
        key: 'change.verbal',
        label: 'Allowing verbal changes is a leading cause of payment disputes.',
        points: 10,
      },
    ],
  },
  {
    questionKey: 'permitsResponsibleParty',
    label: 'Who is responsible for permits?',
    type: 'select',
    group: 'permits',
    options: [
      { value: 'contractor', label: 'Contractor' },
      { value: 'owner', label: 'Owner' },
    ],
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'insuranceProvided',
    label: 'Will the contractor carry project insurance?',
    type: 'boolean',
    group: 'insurance',
    required: false,
    mode: 'standard',
    drivesClauses: ['insurance.requirements'],
  },
  {
    questionKey: 'workmanshipWarrantyMonths',
    label: 'Workmanship warranty (months)',
    type: 'number',
    group: 'warranty',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'hoa',
    label: 'Is the property subject to an HOA or condo association?',
    type: 'boolean',
    group: 'hoa',
    required: false,
    mode: 'standard',
    drivesAddenda: ['addendum.hoa_condo'],
    riskSignals: [
      {
        whenEquals: [true],
        key: 'hoa',
        label: 'HOA / condo approvals can delay the schedule and add cost.',
        points: 5,
      },
    ],
  },
  {
    questionKey: 'ownerSuppliedMaterials',
    label: 'Will the owner supply any materials?',
    type: 'boolean',
    group: 'scope',
    required: false,
    mode: 'standard',
    drivesClauses: ['owner.supplied_materials'],
    drivesAddenda: ['addendum.owner_supplied_materials'],
    riskSignals: [
      {
        whenEquals: [true],
        key: 'owner.supplied',
        label: 'Owner-supplied materials create delivery, defect, and warranty risk outside Contractor control.',
        points: 10,
      },
    ],
  },
  {
    questionKey: 'financing',
    label: 'Is the project financed?',
    type: 'boolean',
    group: 'pricing',
    required: false,
    mode: 'standard',
    riskSignals: [
      {
        whenEquals: [true],
        key: 'financing',
        label: 'Financing introduces lender disbursement timing and disclosure requirements.',
        points: 8,
      },
    ],
  },
  {
    questionKey: 'siteProtectionConcerns',
    label: 'Are there site protection concerns (landscaping, driveway, existing cracks)?',
    type: 'boolean',
    group: 'risk',
    required: false,
    mode: 'standard',
    drivesClauses: ['site.protection'],
  },
  {
    questionKey: 'weatherSensitive',
    label: 'Is the work weather sensitive?',
    type: 'boolean',
    group: 'schedule',
    required: false,
    mode: 'standard',
    drivesClauses: ['weather.delay'],
  },
  {
    questionKey: 'photoDocumentation',
    label: 'Document the project with before / during / after photos?',
    type: 'boolean',
    group: 'execution',
    required: false,
    mode: 'standard',
    drivesClauses: ['documentation.photos'],
  },
  {
    questionKey: 'subcontractorsUsed',
    label: 'Will subcontractors perform any work?',
    type: 'boolean',
    group: 'execution',
    required: false,
    mode: 'standard',
    drivesClauses: ['contractor.subcontractors'],
  },
  {
    questionKey: 'ownerMailingAddress',
    label: 'Owner mailing address',
    type: 'text',
    group: 'parties',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'ownerPhone',
    label: 'Owner phone',
    type: 'text',
    group: 'parties',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'ownerEmail',
    label: 'Owner email',
    type: 'text',
    group: 'parties',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'workHours',
    label: 'Normal work hours',
    type: 'text',
    group: 'schedule',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'depositAmount',
    label: 'Deposit amount',
    type: 'number',
    group: 'payments',
    required: false,
    mode: 'standard',
    visibleWhen: [{ questionKey: 'depositRequired', equals: [true] }],
  },
  {
    questionKey: 'depositPercent',
    label: 'Deposit percent',
    type: 'number',
    group: 'payments',
    required: false,
    mode: 'standard',
    visibleWhen: [{ questionKey: 'depositRequired', equals: [true] }],
  },
  {
    questionKey: 'depositDueDate',
    label: 'Deposit due date',
    type: 'date',
    group: 'payments',
    required: false,
    mode: 'standard',
    visibleWhen: [{ questionKey: 'depositRequired', equals: [true] }],
  },
  {
    questionKey: 'retainagePercent',
    label: 'Retainage percent',
    type: 'number',
    group: 'payments',
    required: false,
    mode: 'standard',
    visibleWhen: [{ questionKey: 'retainage', equals: [true] }],
  },
  {
    questionKey: 'retainageReleaseDays',
    label: 'Retainage release (days after substantial completion)',
    type: 'number',
    group: 'payments',
    required: false,
    mode: 'standard',
    visibleWhen: [{ questionKey: 'retainage', equals: [true] }],
  },

  // --- Advanced (~+15, plus project-type branches) ---
  {
    questionKey: 'yearBuilt',
    label: 'Year the structure was built',
    type: 'number',
    group: 'property',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'hazardousMaterialsPossible',
    label: 'Could hazardous materials be present (asbestos, lead, mold)?',
    type: 'boolean',
    group: 'risk',
    required: false,
    mode: 'advanced',
    drivesClauses: ['risk.hazardous_materials'],
    drivesAddenda: ['addendum.hazardous_materials'],
    riskSignals: [
      {
        whenEquals: [true],
        key: 'hazmat',
        label: 'Possible hazardous materials require stop-work and qualified remediation.',
        points: 12,
      },
    ],
  },
  {
    questionKey: 'allowances',
    label: 'Does the price include selection allowances?',
    type: 'boolean',
    group: 'pricing',
    required: false,
    mode: 'advanced',
    drivesAddenda: ['addendum.allowance_schedule'],
    riskSignals: [
      {
        whenEquals: [true],
        key: 'allowances',
        label: 'Allowances frequently exceed budget once selections are made.',
        points: 8,
      },
    ],
  },
  {
    questionKey: 'materialEscalationConcern',
    label: 'Are material price increases a concern?',
    type: 'boolean',
    group: 'risk',
    required: false,
    mode: 'advanced',
    drivesClauses: ['risk.material_escalation'],
  },
  {
    questionKey: 'disputeMethod',
    label: 'Dispute resolution method',
    type: 'select',
    group: 'compliance',
    options: [
      { value: 'mediation', label: 'Mediation' },
      { value: 'arbitration', label: 'Arbitration' },
      { value: 'litigation', label: 'Litigation' },
    ],
    required: false,
    mode: 'advanced',
    drivesClauses: ['dispute.resolution'],
  },
  {
    questionKey: 'disputeVenue',
    label: 'Dispute venue (county / state)',
    type: 'text',
    group: 'compliance',
    required: false,
    mode: 'advanced',
    visibleWhen: [{ questionKey: 'disputeMethod', equals: ['mediation', 'arbitration', 'litigation'] }],
  },
  {
    questionKey: 'attorneyFees',
    label: 'Include a prevailing-party attorney fees clause?',
    type: 'boolean',
    group: 'compliance',
    required: false,
    mode: 'advanced',
    drivesClauses: ['dispute.attorney_fees'],
  },
  {
    questionKey: 'designBuild',
    label: 'Is the contractor providing design-build services?',
    type: 'boolean',
    group: 'scope',
    required: false,
    mode: 'advanced',
    drivesAddenda: ['addendum.design_build'],
  },

  // Concrete branch
  {
    questionKey: 'concretePsi',
    label: 'Concrete strength (PSI)',
    type: 'number',
    group: 'scope',
    required: false,
    mode: 'advanced',
    visibleWhen: [{ questionKey: 'projectType', equals: ['concrete'] }],
  },
  {
    questionKey: 'concreteSlump',
    label: 'Concrete slump',
    type: 'number',
    group: 'scope',
    required: false,
    mode: 'advanced',
    visibleWhen: [{ questionKey: 'projectType', equals: ['concrete'] }],
  },
  {
    questionKey: 'concreteReinforcement',
    label: 'Reinforcement',
    type: 'select',
    group: 'scope',
    options: [
      { value: 'rebar', label: 'Rebar' },
      { value: 'mesh', label: 'Mesh' },
      { value: 'fiber', label: 'Fiber' },
      { value: 'none', label: 'None' },
    ],
    required: false,
    mode: 'advanced',
    visibleWhen: [{ questionKey: 'projectType', equals: ['concrete'] }],
  },
  {
    questionKey: 'concreteFinish',
    label: 'Finish type',
    type: 'select',
    group: 'scope',
    options: [
      { value: 'broom', label: 'Broom' },
      { value: 'smooth', label: 'Smooth / trowel' },
      { value: 'stamped', label: 'Stamped' },
      { value: 'exposed', label: 'Exposed aggregate' },
    ],
    required: false,
    mode: 'advanced',
    visibleWhen: [{ questionKey: 'projectType', equals: ['concrete'] }],
  },
  {
    questionKey: 'concreteMixDesign',
    label: 'Mix design',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'advanced',
    visibleWhen: [{ questionKey: 'projectType', equals: ['concrete'] }],
  },
  {
    questionKey: 'concreteAir',
    label: 'Air entrainment',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'advanced',
    visibleWhen: [{ questionKey: 'projectType', equals: ['concrete'] }],
  },
  {
    questionKey: 'concreteJointing',
    label: 'Jointing / control joints',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'advanced',
    visibleWhen: [{ questionKey: 'projectType', equals: ['concrete'] }],
  },
  {
    questionKey: 'concreteCuring',
    label: 'Curing method',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'advanced',
    visibleWhen: [{ questionKey: 'projectType', equals: ['concrete'] }],
  },
  {
    questionKey: 'readyMixPlant',
    label: 'Ready-mix plant',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'advanced',
    visibleWhen: [{ questionKey: 'projectType', equals: ['concrete'] }],
    drivesAddenda: ['addendum.ready_mix_order'],
  },
  {
    questionKey: 'readyMixMix',
    label: 'Ready-mix mix code',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'advanced',
    visibleWhen: [{ questionKey: 'projectType', equals: ['concrete'] }],
  },
  {
    questionKey: 'readyMixYards',
    label: 'Yards ordered',
    type: 'number',
    group: 'scope',
    required: false,
    mode: 'advanced',
    visibleWhen: [{ questionKey: 'projectType', equals: ['concrete'] }],
  },
  {
    questionKey: 'readyMixDeliveryDate',
    label: 'Delivery date',
    type: 'date',
    group: 'scope',
    required: false,
    mode: 'advanced',
    visibleWhen: [{ questionKey: 'projectType', equals: ['concrete'] }],
  },
  {
    questionKey: 'readyMixPumpRequired',
    label: 'Pump required?',
    type: 'boolean',
    group: 'scope',
    required: false,
    mode: 'advanced',
    visibleWhen: [{ questionKey: 'projectType', equals: ['concrete'] }],
  },
  {
    questionKey: 'acceptanceFlatness',
    label: 'Acceptance: flatness',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'advanced',
    visibleWhen: [{ questionKey: 'projectType', equals: ['concrete'] }],
    drivesAddenda: ['addendum.concrete_acceptance'],
  },
  {
    questionKey: 'acceptanceLevelness',
    label: 'Acceptance: levelness',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'advanced',
    visibleWhen: [{ questionKey: 'projectType', equals: ['concrete'] }],
  },
  {
    questionKey: 'acceptanceTolerance',
    label: 'Acceptance: tolerance',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'advanced',
    visibleWhen: [{ questionKey: 'projectType', equals: ['concrete'] }],
  },

  // Roofing branch
  {
    questionKey: 'roofShingleType',
    label: 'Roofing material',
    type: 'select',
    group: 'scope',
    options: [
      { value: 'asphalt', label: 'Asphalt shingle' },
      { value: 'metal', label: 'Metal' },
      { value: 'tile', label: 'Tile' },
      { value: 'flat', label: 'Flat / membrane' },
    ],
    required: false,
    mode: 'advanced',
    visibleWhen: [{ questionKey: 'projectType', equals: ['roofing'] }],
    drivesAddenda: ['addendum.roofing'],
  },
  {
    questionKey: 'roofDeckReplacement',
    label: 'Is deck replacement anticipated?',
    type: 'boolean',
    group: 'scope',
    required: false,
    mode: 'advanced',
    visibleWhen: [{ questionKey: 'projectType', equals: ['roofing'] }],
    drivesClauses: ['change_order.unknown_conditions'],
  },

  // Insurance restoration branch
  {
    questionKey: 'insuranceClaimNumber',
    label: 'Insurance claim number',
    type: 'text',
    group: 'insurance',
    required: false,
    mode: 'advanced',
    visibleWhen: [{ questionKey: 'projectType', equals: ['insurance_restoration'] }],
    drivesAddenda: ['addendum.insurance_restoration'],
  },
  {
    questionKey: 'insuranceCarrier',
    label: 'Insurance carrier',
    type: 'text',
    group: 'insurance',
    required: false,
    mode: 'advanced',
    visibleWhen: [{ questionKey: 'projectType', equals: ['insurance_restoration'] }],
  },
  {
    questionKey: 'insuranceAdjuster',
    label: 'Adjuster name',
    type: 'text',
    group: 'insurance',
    required: false,
    mode: 'advanced',
    visibleWhen: [{ questionKey: 'projectType', equals: ['insurance_restoration'] }],
  },

  // Time & materials branch
  {
    questionKey: 'tmRatesConfirmed',
    label: 'Have labor / markup rates been confirmed?',
    type: 'boolean',
    group: 'pricing',
    required: false,
    mode: 'advanced',
    visibleWhen: [{ questionKey: 'priceModel', equals: ['time_and_materials'] }],
    drivesAddenda: ['addendum.time_materials'],
  },
];
