import jsPDF from 'jspdf';
import { format } from 'date-fns';
import { savePDFWithPlatformSupport } from '../../../utils/pdf';
import type { DocumentAssemblyResult, DocumentRiskScore } from '../index';
import { cleanDocumentBody } from './previewDisplay';
import {
  buildResidentialContractDisplayContext,
  filterVisibleRows,
} from './renderers/residentialContractContext';

const MARGIN = 18;
const FOOTER_HEIGHT = 14;

const RISK_LABEL: Record<string, string> = {
  low: 'Low',
  medium: 'Medium',
  high: 'High',
  extreme: 'Extreme',
};

export interface ContractPdfCompanyHeader {
  companyName: string;
  address: string;
  phone: string;
  email?: string;
  licenseNumber?: string;
}

function ensureSpace(doc: jsPDF, y: { value: number }, needed: number) {
  const pageHeight = doc.internal.pageSize.height;
  if (y.value + needed > pageHeight - MARGIN - FOOTER_HEIGHT) {
    doc.addPage();
    y.value = MARGIN;
  }
}

function drawBox(doc: jsPDF, x: number, top: number, width: number, height: number) {
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.rect(x, top, width, height);
}

function addFooter(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(120, 120, 120);
    doc.text(
      `Generated by Concrete Calc · Page ${page} of ${pageCount}`,
      pageWidth / 2,
      pageHeight - 8,
      { align: 'center' },
    );
  }
}

function addInfoBox(
  doc: jsPDF,
  y: { value: number },
  pageWidth: number,
  title: string,
  rows: { label: string; value: string }[],
) {
  if (rows.length === 0) return;
  const boxWidth = pageWidth - MARGIN * 2;
  const padding = 4;
  const lineHeight = 5;
  let contentHeight = padding * 2 + 6;
  for (const row of rows) {
    const valueLines = doc.splitTextToSize(row.value, boxWidth - 52);
    contentHeight += Math.max(lineHeight, valueLines.length * lineHeight);
  }
  ensureSpace(doc, y, contentHeight + 6);
  const boxY = y.value;
  drawBox(doc, MARGIN, boxY, boxWidth, contentHeight);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(90, 90, 90);
  doc.text(title.toUpperCase(), MARGIN + padding, boxY + padding + 4);
  let rowY = boxY + padding + 10;
  doc.setFontSize(9);
  for (const row of rows) {
    ensureSpace(doc, y, 8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(60, 60, 60);
    doc.text(`${row.label}:`, MARGIN + padding, rowY);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);
    const valueLines = doc.splitTextToSize(row.value, boxWidth - 52);
    doc.text(valueLines, MARGIN + 48, rowY);
    rowY += Math.max(lineHeight, valueLines.length * lineHeight);
  }
  y.value = boxY + contentHeight + 6;
}

function addParagraphBlock(
  doc: jsPDF,
  y: { value: number },
  pageWidth: number,
  title: string,
  body: string,
) {
  const maxWidth = pageWidth - MARGIN * 2;
  const cleaned = cleanDocumentBody(body);
  ensureSpace(doc, y, 16);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(90, 90, 90);
  doc.text('SECTION', MARGIN, y.value);
  y.value += 5;
  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  doc.text(title, MARGIN, y.value);
  y.value += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  const lines = doc.splitTextToSize(cleaned || 'Not provided', maxWidth);
  for (const line of lines) {
    ensureSpace(doc, y, 6);
    doc.text(line, MARGIN, y.value);
    y.value += 5;
  }
  y.value += 4;
}

function drawSignatureBox(
  doc: jsPDF,
  x: number,
  top: number,
  width: number,
  role: string,
  name: string | null,
) {
  const boxHeight = 36;
  drawBox(doc, x, top, width, boxHeight);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(90, 90, 90);
  doc.text(role.toUpperCase(), x + 4, top + 7);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  doc.text(`Printed name: ${name?.trim() || '—'}`, x + 4, top + 14);
  doc.setDrawColor(180, 180, 180);
  doc.line(x + 4, top + 28, x + width - 4, top + 28);
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text('Signature', x + 4, top + 27);
  doc.text('Date', x + 4, top + 34);
  return boxHeight;
}

/**
 * Export an assembled draft contract to PDF. Display/formatting only — all
 * document content comes from the engine's assembly result.
 */
export async function exportContractDraftPdf(
  result: DocumentAssemblyResult,
  risk: DocumentRiskScore,
  company: ContractPdfCompanyHeader,
  options: {
    answers?: Record<string, unknown>;
    documentTitle?: string;
    complianceWarningCount?: number;
  } = {},
): Promise<boolean> {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const y = { value: MARGIN };
  const generatedAt = format(new Date(), 'MMMM d, yyyy h:mm a');
  const context = buildResidentialContractDisplayContext({
    answers: options.answers ?? result.manifest.inputSnapshot.answers ?? {},
    companySettings: {
      companyName: company.companyName,
      address: company.address,
      phone: company.phone,
      email: company.email,
      licenseNumber: company.licenseNumber,
      logoUrl: null,
    },
    selectedProject: null,
  });

  // Company header (left)
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text(context.company.name, MARGIN, y.value);
  y.value += 6;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(60, 60, 60);
  if (context.company.address) {
    const addressLines = doc.splitTextToSize(context.company.address, pageWidth - 80);
    doc.text(addressLines, MARGIN, y.value);
    y.value += addressLines.length * 4 + 2;
  }
  const contact: string[] = [];
  if (context.company.phone) contact.push(context.company.phone);
  if (context.company.email) contact.push(context.company.email);
  if (context.company.licenseNumber) contact.push(`License ${context.company.licenseNumber}`);
  if (contact.length) {
    doc.text(contact.join(' · '), MARGIN, y.value);
    y.value += 5;
  }

  // Document type box (right)
  const boxWidth = 58;
  const boxX = pageWidth - MARGIN - boxWidth;
  const boxY = MARGIN - 2;
  drawBox(doc, boxX, boxY, boxWidth, 24);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(70, 70, 70);
  doc.text('RESIDENTIAL CONTRACT', boxX + boxWidth / 2, boxY + 8, { align: 'center' });
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  doc.text('Draft', boxX + boxWidth / 2, boxY + 14, { align: 'center' });
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text(`Date: ${context.documentDate}`, boxX + boxWidth / 2, boxY + 19, {
    align: 'center',
  });

  y.value = Math.max(y.value, boxY + 28);
  doc.setDrawColor(200, 200, 200);
  doc.line(MARGIN, y.value, pageWidth - MARGIN, y.value);
  y.value += 8;

  const docTitle = options.documentTitle?.trim() || result.title || 'Residential Construction Agreement';
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text(docTitle, MARGIN, y.value);
  y.value += 6;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated ${generatedAt}`, MARGIN, y.value);
  y.value += 8;

  addInfoBox(doc, y, pageWidth, 'Project & parties', filterVisibleRows(context.parties));
  addInfoBox(doc, y, pageWidth, 'Contract summary', filterVisibleRows(context.summary));

  addInfoBox(doc, y, pageWidth, 'Legal / draft notice', [
    { label: 'Notice', value: result.disclaimer },
    {
      label: 'Review',
      value:
        'Attorney review is recommended. Verify state, local, licensing, permit, lien, notice, warranty, and cancellation requirements before use.',
    },
  ]);

  addInfoBox(doc, y, pageWidth, 'Risk summary', [
    { label: 'Score', value: `${risk.score} / 100` },
    { label: 'Level', value: RISK_LABEL[risk.level] ?? risk.level },
    ...(options.complianceWarningCount
      ? [{ label: 'Compliance flags', value: String(options.complianceWarningCount) }]
      : []),
  ]);

  for (const section of result.sections) {
    addParagraphBlock(doc, y, pageWidth, section.title, section.body);
  }

  ensureSpace(doc, y, 50);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(80, 80, 80);
  doc.text('SIGNATURES', MARGIN, y.value);
  y.value += 8;

  const signatureBoxWidth = (pageWidth - MARGIN * 2 - 6) / 2;
  const signatureTop = y.value;
  drawSignatureBox(
    doc,
    MARGIN,
    signatureTop,
    signatureBoxWidth,
    'Contractor',
    context.signatures.contractorName,
  );
  drawSignatureBox(
    doc,
    MARGIN + signatureBoxWidth + 6,
    signatureTop,
    signatureBoxWidth,
    'Owner / Client',
    context.signatures.ownerName,
  );
  y.value = signatureTop + 42;

  addFooter(doc);

  const slug = (result.packKey || 'contract').toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40);
  const filename = `contract-draft-${slug}-${Date.now()}.pdf`;
  return savePDFWithPlatformSupport(doc, filename, 'Residential Contract Draft');
}
