import jsPDF from 'jspdf';
import { savePDFWithPlatformSupport } from '../../../../utils/pdf';
import type { DailyReportDocumentView } from '../adapters/dailyReportPreviewAdapter';

const MARGIN = 18;
const FOOTER_HEIGHT = 14;

function ensureSpace(doc: jsPDF, y: { value: number }, needed: number) {
  const pageHeight = doc.internal.pageSize.height;
  if (y.value + needed > pageHeight - MARGIN - FOOTER_HEIGHT) {
    doc.addPage();
    y.value = MARGIN;
  }
}

function drawBox(doc: jsPDF, x: number, top: number, width: number, height: number) {
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.rect(x, top, width, height);
}

function addFooter(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(120, 120, 120);
    doc.text(
      `Generated by Concrete Calc · Page ${page} of ${pageCount}`,
      pageWidth / 2,
      pageHeight - 8,
      { align: 'center' },
    );
  }
}

function addInfoBox(
  doc: jsPDF,
  y: { value: number },
  pageWidth: number,
  title: string,
  rows: { label: string; value: string }[],
) {
  if (rows.length === 0) return;
  const boxWidth = pageWidth - MARGIN * 2;
  const padding = 4;
  const lineHeight = 5;
  let contentHeight = padding * 2 + 6;
  for (const row of rows) {
    const valueLines = doc.splitTextToSize(row.value, boxWidth - 52);
    contentHeight += Math.max(lineHeight, valueLines.length * lineHeight);
  }
  ensureSpace(doc, y, contentHeight + 6);
  const boxY = y.value;
  drawBox(doc, MARGIN, boxY, boxWidth, contentHeight);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(90, 90, 90);
  doc.text(title.toUpperCase(), MARGIN + padding, boxY + padding + 4);
  let rowY = boxY + padding + 10;
  doc.setFontSize(9);
  for (const row of rows) {
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(60, 60, 60);
    doc.text(`${row.label}:`, MARGIN + padding, rowY);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);
    const valueLines = doc.splitTextToSize(row.value, boxWidth - 52);
    doc.text(valueLines, MARGIN + 48, rowY);
    rowY += Math.max(lineHeight, valueLines.length * lineHeight);
  }
  y.value = boxY + contentHeight + 6;
}

function addSection(
  doc: jsPDF,
  y: { value: number },
  pageWidth: number,
  title: string,
  body: string,
) {
  if (!body.trim()) return;
  const maxWidth = pageWidth - MARGIN * 2;
  ensureSpace(doc, y, 20);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(80, 80, 80);
  doc.text(title.toUpperCase(), MARGIN, y.value);
  y.value += 5;
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  const lines = doc.splitTextToSize(body, maxWidth);
  for (const line of lines) {
    ensureSpace(doc, y, 6);
    doc.text(line, MARGIN, y.value);
    y.value += 5;
  }
  y.value += 3;
}

function lineIf(label: string, value: string): string | null {
  if (value === '—' || !value.trim()) return null;
  return `${label}: ${value}`;
}

function joinLines(parts: (string | null)[]): string {
  return parts.filter(Boolean).join('\n');
}

/**
 * Export a professional Daily Report draft PDF from the adapter view model.
 */
export async function generateDailyReportPDF(view: DailyReportDocumentView): Promise<void> {
  const doc = new jsPDF({ unit: 'mm', format: 'letter' });
  const pageWidth = doc.internal.pageSize.width;
  const y = { value: MARGIN };

  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(view.company.name, MARGIN, y.value);
  y.value += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  if (view.company.address) {
    const addrLines = doc.splitTextToSize(view.company.address, pageWidth - MARGIN * 2);
    doc.text(addrLines, MARGIN, y.value);
    y.value += addrLines.length * 5;
  }
  const contact = [view.company.phone, view.company.email].filter(Boolean).join(' · ');
  if (contact) {
    doc.text(contact, MARGIN, y.value);
    y.value += 6;
  }

  const boxW = 55;
  const boxX = pageWidth - MARGIN - boxW;
  drawBox(doc, boxX, MARGIN, boxW, 28);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('DAILY REPORT', boxX + 4, MARGIN + 8);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(view.documentNumber, boxX + 4, MARGIN + 14);
  doc.setFontSize(9);
  doc.text(`Date: ${view.generatedDate}`, boxX + 4, MARGIN + 20);
  doc.text(`Status: ${view.status}`, boxX + 4, MARGIN + 26);

  y.value = Math.max(y.value, MARGIN + 32);

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  const titleLines = doc.splitTextToSize(view.documentTitle, pageWidth - MARGIN * 2);
  doc.text(titleLines, MARGIN, y.value);
  y.value += titleLines.length * 7 + 4;

  const projectRows = view.projectRows.map((row) => ({
    label: row.label,
    value: row.value ?? '—',
  }));
  addInfoBox(doc, y, pageWidth, 'Project Information', projectRows);

  addSection(
    doc,
    y,
    pageWidth,
    'Weather / Site Conditions',
    joinLines([
      lineIf('Weather', view.weatherConditions),
      lineIf('Temperature', view.temperature),
      lineIf('Rain', view.rain),
      lineIf('Wind', view.wind),
      lineIf('Site conditions', view.siteConditions),
    ]),
  );

  addSection(
    doc,
    y,
    pageWidth,
    'Labor / Crew',
    joinLines([
      lineIf('Crew summary', view.crewSummary),
      lineIf('Crew members', view.crewMembers),
      lineIf('Trade', view.trade),
      lineIf('Hours worked', view.hoursWorked),
      lineIf('Foreman / lead', view.foremanLead),
    ]),
  );

  addSection(
    doc,
    y,
    pageWidth,
    'Equipment',
    joinLines([
      lineIf('Equipment used', view.equipmentUsed),
      lineIf('Equipment hours', view.equipmentHours),
      lineIf('Idle equipment', view.idleEquipment),
      lineIf('Equipment issues', view.equipmentIssues),
    ]),
  );

  addSection(
    doc,
    y,
    pageWidth,
    'Work Performed',
    joinLines([
      lineIf('Work completed', view.workPerformed),
      lineIf('Work areas', view.workAreas),
      lineIf('Quantities installed', view.quantitiesInstalled),
    ]),
  );

  addSection(
    doc,
    y,
    pageWidth,
    'Deliveries',
    joinLines([
      lineIf('Deliveries', view.deliveries),
      lineIf('Ticket numbers', view.deliveryTicketNumbers),
      lineIf('Supplier', view.supplier),
      lineIf('Accepted / rejected', view.materialsAcceptedRejected),
    ]),
  );

  const delaysBody = joinLines([
    lineIf('Delays', view.delays),
    lineIf('Cause', view.delayCause),
    lineIf('Responsible party', view.responsibleParty),
    lineIf('Schedule impact', view.scheduleImpact),
  ]);
  if (delaysBody) {
    addSection(doc, y, pageWidth, 'Delays / Impacts', delaysBody);
  }

  addSection(
    doc,
    y,
    pageWidth,
    'Visitors / Inspections',
    joinLines([
      lineIf('Visitors', view.visitors),
      lineIf('Inspectors', view.inspectors),
      lineIf('Owner / A/E visits', view.ownerArchitectEngineerVisits),
    ]),
  );

  addSection(
    doc,
    y,
    pageWidth,
    'Safety Notes',
    joinLines([
      lineIf('Notes', view.safetyNotes),
      lineIf('Safety meeting held', view.safetyMeetingHeld),
      lineIf('Incidents / near misses', view.incidentsNearMisses),
      lineIf('PPE issues', view.ppeIssues),
      lineIf('Corrective actions', view.correctiveActions),
    ]),
  );

  addSection(
    doc,
    y,
    pageWidth,
    'QC Notes',
    joinLines([
      lineIf('Notes', view.qcNotes),
      lineIf('Inspections performed', view.inspectionsPerformed),
      lineIf('Deficiencies', view.deficiencies),
      lineIf('Tests performed', view.testsPerformed),
      lineIf('Follow-up required', view.followUpRequired),
    ]),
  );

  addSection(
    doc,
    y,
    pageWidth,
    'Photos / Attachments',
    joinLines([lineIf('Photo log', view.photos), lineIf('Attachment notes', view.attachmentNotes)]),
  );

  addSection(
    doc,
    y,
    pageWidth,
    'Signature / Acknowledgment',
    joinLines([
      lineIf('Prepared by', view.signaturePreparedBy),
      lineIf('Reviewed by', view.signatureReviewedBy),
      lineIf('Date', view.signatureDate),
    ]),
  );

  addFooter(doc);

  const slugSource =
    view.documentNumber !== 'Draft' ? view.documentNumber : view.generatedDate;
  const safeSlug = slugSource.replace(/[^\w.-]+/g, '_');
  await savePDFWithPlatformSupport(doc, `DAILY-REPORT-${safeSlug}.pdf`);
}
