import jsPDF from 'jspdf';
import { savePDFWithPlatformSupport } from '../../../../utils/pdf';
import type { FarDocumentView } from '../adapters/farPreviewAdapter';

const MARGIN = 18;
const FOOTER_HEIGHT = 14;

function ensureSpace(doc: jsPDF, y: { value: number }, needed: number) {
  const pageHeight = doc.internal.pageSize.height;
  if (y.value + needed > pageHeight - MARGIN - FOOTER_HEIGHT) {
    doc.addPage();
    y.value = MARGIN;
  }
}

function drawBox(doc: jsPDF, x: number, top: number, width: number, height: number) {
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.rect(x, top, width, height);
}

function addFooter(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(120, 120, 120);
    doc.text(
      `Generated by Concrete Calc · Page ${page} of ${pageCount}`,
      pageWidth / 2,
      pageHeight - 8,
      { align: 'center' },
    );
  }
}

function addInfoBox(
  doc: jsPDF,
  y: { value: number },
  pageWidth: number,
  title: string,
  rows: Array<{ label: string; value?: string | null }>,
) {
  if (rows.length === 0) return;
  const boxWidth = pageWidth - MARGIN * 2;
  const padding = 4;
  const lineHeight = 5;
  let contentHeight = padding * 2 + 6;
  for (const row of rows) {
    const rowValue = row.value ?? '—';
    const valueLines = doc.splitTextToSize(rowValue, boxWidth - 52);
    contentHeight += Math.max(lineHeight, valueLines.length * lineHeight);
  }
  ensureSpace(doc, y, contentHeight + 6);
  const boxY = y.value;
  drawBox(doc, MARGIN, boxY, boxWidth, contentHeight);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(90, 90, 90);
  doc.text(title.toUpperCase(), MARGIN + padding, boxY + padding + 4);
  let rowY = boxY + padding + 10;
  doc.setFontSize(9);
  for (const row of rows) {
    const rowValue = row.value ?? '—';
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(60, 60, 60);
    doc.text(`${row.label}:`, MARGIN + padding, rowY);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);
    const valueLines = doc.splitTextToSize(rowValue, boxWidth - 52);
    doc.text(valueLines, MARGIN + 48, rowY);
    rowY += Math.max(lineHeight, valueLines.length * lineHeight);
  }
  y.value = boxY + contentHeight + 6;
}

function addSection(doc: jsPDF, y: { value: number }, pageWidth: number, title: string, body: string) {
  const maxWidth = pageWidth - MARGIN * 2;
  ensureSpace(doc, y, 20);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(80, 80, 80);
  doc.text(title.toUpperCase(), MARGIN, y.value);
  y.value += 5;
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  const lines = doc.splitTextToSize(body, maxWidth);
  for (const line of lines) {
    ensureSpace(doc, y, 6);
    doc.text(line, MARGIN, y.value);
    y.value += 5;
  }
  y.value += 3;
}

export async function generateFarPDF(view: FarDocumentView): Promise<void> {
  const doc = new jsPDF({ unit: 'mm', format: 'letter' });
  const pageWidth = doc.internal.pageSize.width;
  const y = { value: MARGIN };

  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(view.company.name, MARGIN, y.value);
  y.value += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  if (view.company.address) {
    const addrLines = doc.splitTextToSize(view.company.address, pageWidth - MARGIN * 2);
    doc.text(addrLines, MARGIN, y.value);
    y.value += addrLines.length * 5;
  }

  const boxW = 55;
  const boxX = pageWidth - MARGIN - boxW;
  drawBox(doc, boxX, MARGIN, boxW, 28);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('FAR', boxX + 4, MARGIN + 8);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(view.documentNumber, boxX + 4, MARGIN + 14);
  doc.setFontSize(9);
  doc.text(`Date: ${view.generatedDate}`, boxX + 4, MARGIN + 20);
  doc.text(`Status: ${view.status}`, boxX + 4, MARGIN + 26);

  y.value = Math.max(y.value, MARGIN + 32);

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  const titleLines = doc.splitTextToSize(view.documentTitle, pageWidth - MARGIN * 2);
  doc.text(titleLines, MARGIN, y.value);
  y.value += titleLines.length * 7 + 4;

  addInfoBox(doc, y, pageWidth, 'Project Information', view.projectRows);
  addSection(doc, y, pageWidth, 'Description', view.description);
  addSection(doc, y, pageWidth, 'Reason', view.reason);
  addSection(doc, y, pageWidth, 'Proposed Adjustment', view.proposedAdjustment);
  addSection(
    doc,
    y,
    pageWidth,
    'Impact',
    `Labor: ${view.laborImpact}\nMaterial: ${view.materialImpact}\nCost: ${view.costImpact}\nSchedule: ${view.scheduleImpact}`,
  );
  addSection(
    doc,
    y,
    pageWidth,
    'Reviewer Response',
    `${view.reviewerResponse}\n\nReviewed by: ${view.reviewedBy}\nDecision: ${view.approvalDecision}`,
  );

  addFooter(doc);
  const safeNumber = view.documentNumber.replace(/[^\w.-]+/g, '_');
  await savePDFWithPlatformSupport(doc, `FAR-${safeNumber}.pdf`);
}
