import jsPDF from 'jspdf';
import { savePDFWithPlatformSupport } from '../../../../utils/pdf';
import type { PunchListDocumentView, PunchListItemView } from '../adapters/punchListPreviewAdapter';

const MARGIN = 18;
const FOOTER_HEIGHT = 14;
const ROW_HEIGHT = 5;

function ensureSpace(doc: jsPDF, y: { value: number }, needed: number) {
  const pageHeight = doc.internal.pageSize.height;
  if (y.value + needed > pageHeight - MARGIN - FOOTER_HEIGHT) {
    doc.addPage();
    y.value = MARGIN;
  }
}

function drawBox(doc: jsPDF, x: number, top: number, width: number, height: number) {
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.rect(x, top, width, height);
}

function addFooter(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(120, 120, 120);
    doc.text(
      `Generated by Concrete Calc · Page ${page} of ${pageCount}`,
      pageWidth / 2,
      pageHeight - 8,
      { align: 'center' },
    );
  }
}

function addInfoBox(
  doc: jsPDF,
  y: { value: number },
  pageWidth: number,
  title: string,
  rows: { label: string; value: string }[],
) {
  if (rows.length === 0) return;
  const boxWidth = pageWidth - MARGIN * 2;
  const padding = 4;
  const lineHeight = 5;
  let contentHeight = padding * 2 + 6;
  for (const row of rows) {
    const valueLines = doc.splitTextToSize(row.value, boxWidth - 52);
    contentHeight += Math.max(lineHeight, valueLines.length * lineHeight);
  }
  ensureSpace(doc, y, contentHeight + 6);
  const boxY = y.value;
  drawBox(doc, MARGIN, boxY, boxWidth, contentHeight);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(90, 90, 90);
  doc.text(title.toUpperCase(), MARGIN + padding, boxY + padding + 4);
  let rowY = boxY + padding + 10;
  doc.setFontSize(9);
  for (const row of rows) {
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(60, 60, 60);
    doc.text(`${row.label}:`, MARGIN + padding, rowY);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);
    const valueLines = doc.splitTextToSize(row.value, boxWidth - 52);
    doc.text(valueLines, MARGIN + 48, rowY);
    rowY += Math.max(lineHeight, valueLines.length * lineHeight);
  }
  y.value = boxY + contentHeight + 6;
}

function addSection(
  doc: jsPDF,
  y: { value: number },
  pageWidth: number,
  title: string,
  body: string,
) {
  if (!body.trim()) return;
  const maxWidth = pageWidth - MARGIN * 2;
  ensureSpace(doc, y, 20);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(80, 80, 80);
  doc.text(title.toUpperCase(), MARGIN, y.value);
  y.value += 5;
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  const lines = doc.splitTextToSize(body, maxWidth);
  for (const line of lines) {
    ensureSpace(doc, y, 6);
    doc.text(line, MARGIN, y.value);
    y.value += 5;
  }
  y.value += 3;
}

function lineIf(label: string, value: string): string | null {
  if (value === '—' || !value.trim()) return null;
  return `${label}: ${value}`;
}

function joinLines(parts: (string | null)[]): string {
  return parts.filter(Boolean).join('\n');
}

function hasAny(...values: string[]): boolean {
  return values.some((v) => v !== '—' && v.trim() !== '');
}

function cellText(value: string, maxLen: number): string {
  if (value === '—' || !value.trim()) return '—';
  const t = value.replace(/\s+/g, ' ').trim();
  return t.length > maxLen ? `${t.slice(0, maxLen - 1)}…` : t;
}

function addPunchItemsSummaryTable(
  doc: jsPDF,
  y: { value: number },
  pageWidth: number,
  items: PunchListItemView[],
) {
  if (items.length === 0) return;

  const tableWidth = pageWidth - MARGIN * 2;
  const cols = [
    { label: '#', width: 10 },
    { label: 'Location', width: 28 },
    { label: 'Description', width: 52 },
    { label: 'Resp.', width: 22 },
    { label: 'Pri.', width: 14 },
    { label: 'Status', width: 22 },
    { label: 'Due', width: 18 },
  ];
  const totalColWidth = cols.reduce((s, c) => s + c.width, 0);
  const scale = tableWidth / totalColWidth;

  ensureSpace(doc, y, 16 + items.length * ROW_HEIGHT);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(80, 80, 80);
  doc.text('PUNCH LIST ITEMS', MARGIN, y.value);
  y.value += 6;

  let x = MARGIN;
  doc.setFontSize(7);
  doc.setTextColor(90, 90, 90);
  for (const col of cols) {
    const w = col.width * scale;
    doc.text(col.label, x + 1, y.value);
    x += w;
  }
  y.value += 4;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(0, 0, 0);

  for (const item of items) {
    ensureSpace(doc, y, ROW_HEIGHT + 2);
    x = MARGIN;
    const rowValues = [
      cellText(item.itemNumber, 8),
      cellText(item.locationArea, 22),
      cellText(item.itemDescription, 40),
      cellText(item.responsibleParty, 18),
      cellText(item.priority, 10),
      cellText(item.itemStatus, 18),
      cellText(item.dueDate, 14),
    ];
    cols.forEach((col, i) => {
      const w = col.width * scale;
      const lines = doc.splitTextToSize(rowValues[i], w - 2);
      doc.text(lines[0] ?? '—', x + 1, y.value);
      x += w;
    });
    y.value += ROW_HEIGHT;
  }
  y.value += 4;
}

function formatItemDetailBlock(item: PunchListItemView): string {
  return joinLines([
    lineIf('Description', item.itemDescription),
    lineIf('Location', item.locationArea),
    lineIf('Category', item.category),
    lineIf('Trade', item.trade),
    lineIf('Responsible', item.responsibleParty),
    lineIf('Priority', item.priority),
    lineIf('Status', item.itemStatus),
    lineIf('Due', item.dueDate),
    lineIf('Corrective action', item.correctiveAction),
    lineIf('Completed', item.completionDate),
    lineIf('Verified by', item.verifiedBy),
    lineIf('Verified on', item.verificationDate),
    lineIf('Owner comment', item.ownerComment),
    lineIf('Contractor response', item.contractorResponse),
    lineIf('Cost impact', item.costImpact),
    lineIf('Schedule impact', item.scheduleImpact),
    lineIf('Photos', item.photoReferences),
    lineIf('Attachments', item.attachmentNotes),
    lineIf('Notes', item.notes),
  ]);
}

function hasItemDetailExtras(item: PunchListItemView): boolean {
  return hasAny(
    item.category,
    item.trade,
    item.completionDate,
    item.verifiedBy,
    item.verificationDate,
    item.ownerComment,
    item.contractorResponse,
    item.costImpact,
    item.scheduleImpact,
    item.photoReferences,
    item.attachmentNotes,
    item.notes,
  );
}

export async function generatePunchListPDF(view: PunchListDocumentView): Promise<void> {
  const doc = new jsPDF({ unit: 'mm', format: 'letter' });
  const pageWidth = doc.internal.pageSize.width;
  const y = { value: MARGIN };

  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(view.company.name, MARGIN, y.value);
  y.value += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  if (view.company.address) {
    const addrLines = doc.splitTextToSize(view.company.address, pageWidth - MARGIN * 2);
    doc.text(addrLines, MARGIN, y.value);
    y.value += addrLines.length * 5;
  }
  const contact = [view.company.phone, view.company.email].filter(Boolean).join(' · ');
  if (contact) {
    doc.text(contact, MARGIN, y.value);
    y.value += 6;
  }

  const boxW = 55;
  const boxX = pageWidth - MARGIN - boxW;
  drawBox(doc, boxX, MARGIN, boxW, 28);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('PUNCH LIST', boxX + 4, MARGIN + 8);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(view.documentNumber, boxX + 4, MARGIN + 14);
  doc.setFontSize(9);
  doc.text(`Date: ${view.generatedDate}`, boxX + 4, MARGIN + 20);
  doc.text(`Status: ${view.status}`, boxX + 4, MARGIN + 26);

  y.value = Math.max(y.value, MARGIN + 32);

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  const titleLines = doc.splitTextToSize(view.documentTitle, pageWidth - MARGIN * 2);
  doc.text(titleLines, MARGIN, y.value);
  y.value += titleLines.length * 7 + 4;

  const projectRows = view.projectRows.map((row) => ({
    label: row.label,
    value: row.value ?? '—',
  }));
  addInfoBox(doc, y, pageWidth, 'Project Information', projectRows);

  addSection(
    doc,
    y,
    pageWidth,
    'Inspection Summary',
    joinLines([
      lineIf('Inspection date', view.inspectionDate),
      lineIf('Location', view.inspectionLocation),
      lineIf('Overall status', view.status),
      lineIf('Summary', view.summary),
    ]),
  );

  if (view.items.length === 0) {
    addSection(doc, y, pageWidth, 'Punch List Items', 'No punch items recorded.');
  } else {
    addPunchItemsSummaryTable(doc, y, pageWidth, view.items);
    view.items.forEach((item, index) => {
      const detail = formatItemDetailBlock(item);
      if (detail && (view.items.length <= 2 || hasItemDetailExtras(item))) {
        addSection(doc, y, pageWidth, `Item ${item.itemNumber || index + 1} — Details`, detail);
      }
    });
  }

  if (hasAny(view.costImpact, view.scheduleImpact)) {
    addSection(
      doc,
      y,
      pageWidth,
      'Impacts',
      joinLines([
        lineIf('Cost impact', view.costImpact),
        lineIf('Schedule impact', view.scheduleImpact),
      ]),
    );
  }

  const commentsBody = joinLines([
    lineIf('Owner comment', view.ownerComment),
    lineIf('Contractor response', view.contractorResponse),
  ]);
  if (commentsBody) {
    addSection(doc, y, pageWidth, 'Owner / Contractor Comments', commentsBody);
  }

  const attachBody = joinLines([
    lineIf('Photos', view.photoReferences),
    lineIf('Notes', view.attachmentNotes),
  ]);
  if (attachBody) {
    addSection(doc, y, pageWidth, 'Photos / Attachments', attachBody);
  }

  const acceptanceBody = joinLines([
    lineIf('Accepted by', view.finalAcceptanceBy),
    lineIf('Date', view.finalAcceptanceDate),
  ]);
  if (acceptanceBody) {
    addSection(doc, y, pageWidth, 'Final Acceptance', acceptanceBody);
  }

  addSection(
    doc,
    y,
    pageWidth,
    'Signature / Acknowledgment',
    joinLines([
      lineIf('Prepared by', view.signaturePreparedBy),
      lineIf('Verified by', view.signatureVerifiedBy),
      lineIf('Owner / client', view.signatureOwner),
      lineIf('Date', view.signatureDate),
    ]),
  );

  addFooter(doc);

  const slugSource =
    view.documentNumber !== 'Draft' ? view.documentNumber : view.generatedDate;
  const safeSlug = slugSource.replace(/[^\w.-]+/g, '_');
  await savePDFWithPlatformSupport(doc, `PUNCH-LIST-${safeSlug}.pdf`);
}
