import jsPDF from 'jspdf';
import { savePDFWithPlatformSupport } from '../../../../utils/pdf';
import type { QcReportDocumentView } from '../adapters/qcReportPreviewAdapter';

const MARGIN = 18;
const FOOTER_HEIGHT = 14;

function ensureSpace(doc: jsPDF, y: { value: number }, needed: number) {
  const pageHeight = doc.internal.pageSize.height;
  if (y.value + needed > pageHeight - MARGIN - FOOTER_HEIGHT) {
    doc.addPage();
    y.value = MARGIN;
  }
}

function drawBox(doc: jsPDF, x: number, top: number, width: number, height: number) {
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.rect(x, top, width, height);
}

function addFooter(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(120, 120, 120);
    doc.text(
      `Generated by Concrete Calc · Page ${page} of ${pageCount}`,
      pageWidth / 2,
      pageHeight - 8,
      { align: 'center' },
    );
  }
}

function addInfoBox(
  doc: jsPDF,
  y: { value: number },
  pageWidth: number,
  title: string,
  rows: { label: string; value: string }[],
) {
  if (rows.length === 0) return;
  const boxWidth = pageWidth - MARGIN * 2;
  const padding = 4;
  const lineHeight = 5;
  let contentHeight = padding * 2 + 6;
  for (const row of rows) {
    const valueLines = doc.splitTextToSize(row.value, boxWidth - 52);
    contentHeight += Math.max(lineHeight, valueLines.length * lineHeight);
  }
  ensureSpace(doc, y, contentHeight + 6);
  const boxY = y.value;
  drawBox(doc, MARGIN, boxY, boxWidth, contentHeight);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(90, 90, 90);
  doc.text(title.toUpperCase(), MARGIN + padding, boxY + padding + 4);
  let rowY = boxY + padding + 10;
  doc.setFontSize(9);
  for (const row of rows) {
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(60, 60, 60);
    doc.text(`${row.label}:`, MARGIN + padding, rowY);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);
    const valueLines = doc.splitTextToSize(row.value, boxWidth - 52);
    doc.text(valueLines, MARGIN + 48, rowY);
    rowY += Math.max(lineHeight, valueLines.length * lineHeight);
  }
  y.value = boxY + contentHeight + 6;
}

function addSection(
  doc: jsPDF,
  y: { value: number },
  pageWidth: number,
  title: string,
  body: string,
) {
  if (!body.trim()) return;
  const maxWidth = pageWidth - MARGIN * 2;
  ensureSpace(doc, y, 20);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(80, 80, 80);
  doc.text(title.toUpperCase(), MARGIN, y.value);
  y.value += 5;
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  const lines = doc.splitTextToSize(body, maxWidth);
  for (const line of lines) {
    ensureSpace(doc, y, 6);
    doc.text(line, MARGIN, y.value);
    y.value += 5;
  }
  y.value += 3;
}

function lineIf(label: string, value: string): string | null {
  if (value === '—' || !value.trim()) return null;
  return `${label}: ${value}`;
}

function joinLines(parts: (string | null)[]): string {
  return parts.filter(Boolean).join('\n');
}

function hasAny(...values: string[]): boolean {
  return values.some((v) => v !== '—' && v.trim() !== '');
}

/**
 * Export a professional QC Report draft PDF from the adapter view model.
 */
export async function generateQcReportPDF(view: QcReportDocumentView): Promise<void> {
  const doc = new jsPDF({ unit: 'mm', format: 'letter' });
  const pageWidth = doc.internal.pageSize.width;
  const y = { value: MARGIN };

  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(view.company.name, MARGIN, y.value);
  y.value += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  if (view.company.address) {
    const addrLines = doc.splitTextToSize(view.company.address, pageWidth - MARGIN * 2);
    doc.text(addrLines, MARGIN, y.value);
    y.value += addrLines.length * 5;
  }
  const contact = [view.company.phone, view.company.email].filter(Boolean).join(' · ');
  if (contact) {
    doc.text(contact, MARGIN, y.value);
    y.value += 6;
  }

  const boxW = 55;
  const boxX = pageWidth - MARGIN - boxW;
  drawBox(doc, boxX, MARGIN, boxW, 28);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('QC REPORT', boxX + 4, MARGIN + 8);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(view.documentNumber, boxX + 4, MARGIN + 14);
  doc.setFontSize(9);
  doc.text(`Date: ${view.generatedDate}`, boxX + 4, MARGIN + 20);
  doc.text(`Status: ${view.status}`, boxX + 4, MARGIN + 26);

  y.value = Math.max(y.value, MARGIN + 32);

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  const titleLines = doc.splitTextToSize(view.documentTitle, pageWidth - MARGIN * 2);
  doc.text(titleLines, MARGIN, y.value);
  y.value += titleLines.length * 7 + 4;

  const projectRows = view.projectRows.map((row) => ({
    label: row.label,
    value: row.value ?? '—',
  }));
  addInfoBox(doc, y, pageWidth, 'Project Information', projectRows);

  addSection(
    doc,
    y,
    pageWidth,
    'Inspection Overview',
    joinLines([
      lineIf('Inspection type', view.inspectionType),
      lineIf('Location / area', view.inspectionLocation),
      lineIf('Specification', view.specificationReference),
      lineIf('Drawing', view.drawingReference),
      lineIf('Work inspected', view.workInspected),
      lineIf('Overall status', view.status),
      lineIf('Summary', view.summary),
    ]),
  );

  addSection(
    doc,
    y,
    pageWidth,
    'Inspection Details',
    joinLines([
      lineIf('Method', view.inspectionMethod),
      lineIf('Acceptance criteria', view.acceptanceCriteria),
      lineIf('Observations', view.observations),
      lineIf('QC notes', view.qcNotes),
    ]),
  );

  const deficiencyBody = joinLines([
    lineIf('Deficiencies', view.deficiencies),
    lineIf('Corrective actions', view.correctiveActions),
    lineIf('Responsible party', view.responsibleParty),
    lineIf('Follow-up required', view.followUpRequired),
    lineIf('Follow-up date', view.followUpDate),
    lineIf('Reinspection required', view.reinspectionRequired),
    lineIf('Reinspection date', view.reinspectionDate),
  ]);
  if (deficiencyBody) {
    addSection(doc, y, pageWidth, 'Deficiencies / Corrective Actions', deficiencyBody);
  }

  if (
    hasAny(
      view.concretePlacementDate,
      view.mixDesignReference,
      view.truckTicketNumbers,
      view.slump,
      view.airContent,
      view.concreteTemperature,
      view.ambientTemperature,
      view.cylinderSetNumbers,
      view.breakResults,
    )
  ) {
    addSection(
      doc,
      y,
      pageWidth,
      'Concrete QC Data',
      joinLines([
        lineIf('Placement date', view.concretePlacementDate),
        lineIf('Mix design', view.mixDesignReference),
        lineIf('Truck tickets', view.truckTicketNumbers),
        lineIf('Slump', view.slump),
        lineIf('Air content', view.airContent),
        lineIf('Concrete temp', view.concreteTemperature),
        lineIf('Ambient temp', view.ambientTemperature),
        lineIf('Cylinder sets', view.cylinderSetNumbers),
        lineIf('Break results', view.breakResults),
      ]),
    );
  }

  if (hasAny(view.testType, view.testResults, view.testingAgency, view.sampleNumbers)) {
    addSection(
      doc,
      y,
      pageWidth,
      'Testing',
      joinLines([
        lineIf('Test type', view.testType),
        lineIf('Results', view.testResults),
        lineIf('Agency', view.testingAgency),
        lineIf('Samples', view.sampleNumbers),
      ]),
    );
  }

  addSection(
    doc,
    y,
    pageWidth,
    'Inspector / Review',
    joinLines([
      lineIf('Inspector', view.inspectorName),
      lineIf('Company', view.inspectorCompany),
      lineIf('Owner rep', view.ownerRepresentative),
      lineIf('Reviewed by', view.reviewedBy),
    ]),
  );

  addSection(
    doc,
    y,
    pageWidth,
    'Photos / Attachments',
    joinLines([
      lineIf('Photos', view.photos),
      lineIf('Attachments', view.attachments),
      lineIf('Notes', view.attachmentNotes),
    ]),
  );

  addSection(
    doc,
    y,
    pageWidth,
    'Signature / Acknowledgment',
    joinLines([
      lineIf('Prepared by', view.signaturePreparedBy),
      lineIf('Inspector', view.signatureInspector),
      lineIf('Reviewed by', view.signatureReviewedBy),
      lineIf('Date', view.signatureDate),
    ]),
  );

  addFooter(doc);

  const slugSource =
    view.documentNumber !== 'Draft' ? view.documentNumber : view.generatedDate;
  const safeSlug = slugSource.replace(/[^\w.-]+/g, '_');
  await savePDFWithPlatformSupport(doc, `QC-REPORT-${safeSlug}.pdf`);
}
