import jsPDF from 'jspdf';
import { savePDFWithPlatformSupport } from '../../../../utils/pdf';
import type { WarrantyCloseoutDocumentView } from '../adapters/warrantyCloseoutPreviewAdapter';

const MARGIN = 18;
const FOOTER_HEIGHT = 14;

function ensureSpace(doc: jsPDF, y: { value: number }, needed: number) {
  const pageHeight = doc.internal.pageSize.height;
  if (y.value + needed > pageHeight - MARGIN - FOOTER_HEIGHT) {
    doc.addPage();
    y.value = MARGIN;
  }
}

function drawBox(doc: jsPDF, x: number, top: number, width: number, height: number) {
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.rect(x, top, width, height);
}

function addFooter(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(120, 120, 120);
    doc.text(
      `Generated by Arden Project OS · Page ${page} of ${pageCount}`,
      pageWidth / 2,
      pageHeight - 8,
      { align: 'center' },
    );
  }
}

function addInfoBox(
  doc: jsPDF,
  y: { value: number },
  pageWidth: number,
  title: string,
  rows: { label: string; value: string }[],
) {
  if (rows.length === 0) return;
  const boxWidth = pageWidth - MARGIN * 2;
  const padding = 4;
  const lineHeight = 5;
  let contentHeight = padding * 2 + 6;
  for (const row of rows) {
    const valueLines = doc.splitTextToSize(row.value, boxWidth - 52);
    contentHeight += Math.max(lineHeight, valueLines.length * lineHeight);
  }
  ensureSpace(doc, y, contentHeight + 6);
  const boxY = y.value;
  drawBox(doc, MARGIN, boxY, boxWidth, contentHeight);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(90, 90, 90);
  doc.text(title.toUpperCase(), MARGIN + padding, boxY + padding + 4);
  let rowY = boxY + padding + 10;
  doc.setFontSize(9);
  for (const row of rows) {
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(60, 60, 60);
    doc.text(`${row.label}:`, MARGIN + padding, rowY);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);
    const valueLines = doc.splitTextToSize(row.value, boxWidth - 52);
    doc.text(valueLines, MARGIN + 48, rowY);
    rowY += Math.max(lineHeight, valueLines.length * lineHeight);
  }
  y.value = boxY + contentHeight + 6;
}

function addSection(
  doc: jsPDF,
  y: { value: number },
  pageWidth: number,
  title: string,
  body: string,
) {
  if (!body.trim()) return;
  const maxWidth = pageWidth - MARGIN * 2;
  ensureSpace(doc, y, 20);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(80, 80, 80);
  doc.text(title.toUpperCase(), MARGIN, y.value);
  y.value += 5;
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  const lines = doc.splitTextToSize(body, maxWidth);
  for (const line of lines) {
    ensureSpace(doc, y, 6);
    doc.text(line, MARGIN, y.value);
    y.value += 5;
  }
  y.value += 3;
}

function lineIf(label: string, value: string): string | null {
  if (value === '—' || !value.trim()) return null;
  return `${label}: ${value}`;
}

function joinLines(parts: (string | null)[]): string {
  return parts.filter(Boolean).join('\n');
}

function hasAny(...values: string[]): boolean {
  return values.some((v) => v !== '—' && v.trim() !== '');
}

export async function generateWarrantyCloseoutPDF(
  view: WarrantyCloseoutDocumentView,
): Promise<void> {
  const doc = new jsPDF({ unit: 'mm', format: 'letter' });
  const pageWidth = doc.internal.pageSize.width;
  const y = { value: MARGIN };

  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(view.company.name, MARGIN, y.value);
  y.value += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  if (view.company.address) {
    const addrLines = doc.splitTextToSize(view.company.address, pageWidth - MARGIN * 2);
    doc.text(addrLines, MARGIN, y.value);
    y.value += addrLines.length * 5;
  }
  const contact = [view.company.phone, view.company.email].filter(Boolean).join(' · ');
  if (contact) {
    doc.text(contact, MARGIN, y.value);
    y.value += 6;
  }

  const boxW = 62;
  const boxX = pageWidth - MARGIN - boxW;
  drawBox(doc, boxX, MARGIN, boxW, 28);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('WARRANTY / CLOSEOUT', boxX + 4, MARGIN + 8);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(view.documentNumber, boxX + 4, MARGIN + 14);
  doc.setFontSize(9);
  doc.text(`Date: ${view.generatedDate}`, boxX + 4, MARGIN + 20);
  doc.text(`Status: ${view.status}`, boxX + 4, MARGIN + 26);

  y.value = Math.max(y.value, MARGIN + 32);

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  const titleLines = doc.splitTextToSize(view.documentTitle, pageWidth - MARGIN * 2);
  doc.text(titleLines, MARGIN, y.value);
  y.value += titleLines.length * 7 + 4;

  const projectRows = view.projectRows.map((row) => ({
    label: row.label,
    value: row.value ?? '—',
  }));
  addInfoBox(doc, y, pageWidth, 'Project Information', projectRows);

  addSection(
    doc,
    y,
    pageWidth,
    'Closeout Summary',
    joinLines([
      lineIf('Completion date', view.projectCompletionDate),
      lineIf('Final inspection date', view.finalInspectionDate),
      lineIf('Final inspection result', view.finalInspectionResult),
      lineIf('Punch list status', view.punchListStatus),
      lineIf('Summary', view.closeoutSummary),
      lineIf('Scope completed', view.projectScopeCompleted),
    ]),
  );

  addSection(
    doc,
    y,
    pageWidth,
    'Warranty Information',
    joinLines([
      lineIf('Warranty start', view.warrantyStartDate),
      lineIf('Warranty period', view.warrantyPeriod),
      lineIf('Coverage', view.warrantyCoverage),
      lineIf('Exclusions', view.warrantyExclusions),
      lineIf('Owner responsibilities', view.ownerResponsibilities),
      lineIf('Maintenance', view.maintenanceInstructions),
    ]),
  );

  addSection(
    doc,
    y,
    pageWidth,
    'Closeout Documents Included',
    joinLines([
      lineIf('As-built drawings', view.asBuiltDrawingsIncluded),
      lineIf('O&M manuals', view.operationManualsIncluded),
      lineIf('Test reports', view.testReportsIncluded),
      lineIf('Material certifications', view.materialCertificationsIncluded),
      lineIf('Lien waivers', view.lienWaiverStatus),
      lineIf('Keys / access codes', view.keysAccessCodesReturned),
      lineIf('Spare materials', view.spareMaterialsProvided),
      lineIf('Other documents', view.closeoutDocumentsIncluded),
    ]),
  );

  if (hasAny(view.finalPaymentStatus, view.retainageStatus, view.lienWaiverStatus)) {
    addSection(
      doc,
      y,
      pageWidth,
      'Financial / Administrative Status',
      joinLines([
        lineIf('Final payment', view.finalPaymentStatus),
        lineIf('Retainage', view.retainageStatus),
        lineIf('Lien waiver', view.lienWaiverStatus),
      ]),
    );
  }

  const openBody = joinLines([
    lineIf('Unresolved items', view.unresolvedItems),
    lineIf('Follow-up required', view.followUpRequired),
    lineIf('Follow-up date', view.followUpDate),
    lineIf('Additional terms', view.additionalTerms),
  ]);
  if (openBody) {
    addSection(doc, y, pageWidth, 'Open Items / Follow-Up', openBody);
  }

  addSection(
    doc,
    y,
    pageWidth,
    'Contractor Contact',
    joinLines([
      lineIf('Name', view.contractorContactName),
      lineIf('Phone', view.contractorContactPhone),
      lineIf('Email', view.contractorContactEmail),
    ]),
  );

  addSection(
    doc,
    y,
    pageWidth,
    'Attachments / Notes',
    joinLines([lineIf('Notes', view.attachmentNotes)]),
  );

  addSection(
    doc,
    y,
    pageWidth,
    'Signature / Acknowledgment',
    joinLines([
      lineIf('Contractor / prepared by', view.signaturePreparedBy),
      lineIf('Owner / client', view.signatureOwner),
      lineIf('Date', view.signatureDate),
    ]),
  );

  addFooter(doc);

  const slugSource =
    view.documentNumber !== 'Draft' ? view.documentNumber : view.generatedDate;
  const safeSlug = slugSource.replace(/[^\w.-]+/g, '_');
  await savePDFWithPlatformSupport(doc, `WARRANTY-CLOSEOUT-${safeSlug}.pdf`);
}
