import type { DocumentQuestion } from '../../types';

const STATUS_OPTIONS = [
  { value: 'draft', label: 'Draft' },
  { value: 'submitted', label: 'Submitted' },
  { value: 'reviewed', label: 'Reviewed' },
  { value: 'closed', label: 'Closed' },
];

const WEATHER_OPTIONS = [
  { value: 'clear', label: 'Clear' },
  { value: 'cloudy', label: 'Cloudy' },
  { value: 'rain', label: 'Rain' },
  { value: 'windy', label: 'Windy' },
  { value: 'hot', label: 'Hot' },
  { value: 'cold', label: 'Cold' },
  { value: 'severe_weather', label: 'Severe Weather' },
  { value: 'other', label: 'Other' },
];

/**
 * Daily Report Pack question bank for the Document Builder intake form.
 * Answer keys align with `dailyReportPreviewAdapter` and `DailyReportDocument` renderer.
 */
export const dailyReportQuestions: DocumentQuestion[] = [
  // ── Quick mode (field-usable) ───────────────────────────────────────────────
  {
    questionKey: 'reportDate',
    label: 'Report date',
    type: 'date',
    group: 'schedule',
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'preparedBy',
    label: 'Prepared by',
    type: 'text',
    group: 'parties',
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'weatherConditions',
    label: 'Weather conditions',
    type: 'select',
    group: 'schedule',
    options: WEATHER_OPTIONS,
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'crewSummary',
    label: 'Crew summary',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'workPerformed',
    label: 'Work performed',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'reportNumber',
    label: 'Report number',
    type: 'text',
    group: 'schedule',
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'status',
    label: 'Status',
    type: 'select',
    group: 'execution',
    options: STATUS_OPTIONS,
    required: false,
    mode: 'quick',
  },

  // ── Standard mode ─────────────────────────────────────────────────────────
  {
    questionKey: 'temperature',
    label: 'Temperature',
    type: 'text',
    group: 'schedule',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'rain',
    label: 'Rain',
    type: 'text',
    group: 'schedule',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'wind',
    label: 'Wind',
    type: 'text',
    group: 'schedule',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'siteConditions',
    label: 'Site conditions',
    type: 'text',
    group: 'schedule',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'crewMembers',
    label: 'Crew members',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'trade',
    label: 'Trade',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'hoursWorked',
    label: 'Hours worked',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'foremanLead',
    label: 'Foreman / lead',
    type: 'text',
    group: 'parties',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'equipmentUsed',
    label: 'Equipment used',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'deliveries',
    label: 'Material deliveries',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'delays',
    label: 'Delays',
    type: 'text',
    group: 'change_management',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'visitors',
    label: 'Visitors',
    type: 'text',
    group: 'parties',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'safetyNotes',
    label: 'Safety notes',
    type: 'text',
    group: 'risk',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'qcNotes',
    label: 'QC notes',
    type: 'text',
    group: 'compliance',
    required: false,
    mode: 'standard',
  },

  // ── Advanced mode ─────────────────────────────────────────────────────────
  {
    questionKey: 'equipmentHours',
    label: 'Equipment hours',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'idleEquipment',
    label: 'Idle equipment',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'equipmentIssues',
    label: 'Equipment issues',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'quantitiesInstalled',
    label: 'Quantities installed',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'workAreas',
    label: 'Work areas / locations',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'deliveryTicketNumbers',
    label: 'Delivery ticket numbers',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'supplier',
    label: 'Supplier',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'materialsAcceptedRejected',
    label: 'Materials accepted / rejected',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'delayCause',
    label: 'Delay cause',
    type: 'text',
    group: 'change_management',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'responsibleParty',
    label: 'Responsible party',
    type: 'text',
    group: 'change_management',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'scheduleImpact',
    label: 'Schedule impact',
    type: 'text',
    group: 'change_management',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'inspectors',
    label: 'Inspectors',
    type: 'text',
    group: 'parties',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'ownerArchitectEngineerVisits',
    label: 'Owner / architect / engineer visits',
    type: 'text',
    group: 'parties',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'safetyMeetingHeld',
    label: 'Safety meeting held',
    type: 'text',
    group: 'risk',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'incidentsNearMisses',
    label: 'Incidents / near misses',
    type: 'text',
    group: 'risk',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'ppeIssues',
    label: 'PPE issues',
    type: 'text',
    group: 'risk',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'correctiveActions',
    label: 'Corrective actions',
    type: 'text',
    group: 'risk',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'inspectionsPerformed',
    label: 'Inspections performed',
    type: 'text',
    group: 'compliance',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'deficiencies',
    label: 'Deficiencies',
    type: 'text',
    group: 'compliance',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'testsPerformed',
    label: 'Tests performed',
    type: 'text',
    group: 'compliance',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'photos',
    label: 'Photo log',
    type: 'text',
    group: 'execution',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'followUpRequired',
    label: 'Follow-up required',
    type: 'text',
    group: 'compliance',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'attachmentNotes',
    label: 'Attachment notes',
    type: 'text',
    group: 'execution',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'reviewedBy',
    label: 'Reviewed by',
    type: 'text',
    group: 'execution',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'signatureDate',
    label: 'Signature date',
    type: 'date',
    group: 'execution',
    required: false,
    mode: 'advanced',
  },
];
