import {
  fittingDefinition,
} from './plumbingFittingCompatibility';
import type { PlumbingFitting, PlumbingFittingType } from '../plumbingFittingTypes';
import type {
  PlumbingElevationMode,
  PlumbingMaterial,
  PlumbingNode,
  PlumbingPoint3D,
  PlumbingRun,
  PlumbingRunSystem,
  PlumbingSystem,
} from '../plumbingTypes';

function createId(prefix: string): string {
  return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

function pointsNearlyEqual(a: PlumbingPoint3D, b: PlumbingPoint3D): boolean {
  return Math.hypot(a.x - b.x, a.z - b.z) <= 0.01;
}

function angleBetween(a: PlumbingPoint3D, b: PlumbingPoint3D, c: PlumbingPoint3D): number {
  const v1 = { x: a.x - b.x, z: a.z - b.z };
  const v2 = { x: c.x - b.x, z: c.z - b.z };
  const dot = v1.x * v2.x + v1.z * v2.z;
  const mag = Math.hypot(v1.x, v1.z) * Math.hypot(v2.x, v2.z);
  if (mag <= 0) return 180;
  return Math.acos(Math.max(-1, Math.min(1, dot / mag))) * 180 / Math.PI;
}

function fittingForBend(system: PlumbingRunSystem, bendDegrees: number): PlumbingFittingType {
  const turn = Math.abs(180 - bendDegrees);
  if (Math.abs(turn - 90) <= 15) return system === 'sanitary' ? 'elbow_90_long_sweep' : 'elbow_90';
  if (Math.abs(turn - 45) <= 12) return 'elbow_45';
  if (Math.abs(turn - 22.5) <= 8) return 'elbow_22_5';
  return 'offset_bend';
}

function primaryRunAtNode(runs: PlumbingRun[], nodeId: string): PlumbingRun | null {
  return runs.find((run) => run.startNodeId === nodeId || run.endNodeId === nodeId) ?? null;
}

function fittingForConnectedRuns(runs: PlumbingRun[]): PlumbingFittingType {
  const systems = new Set(runs.map((run) => run.system));
  const system = systems.size === 1 ? runs[0]?.system : null;
  const materials = new Set(runs.map((run) => run.material));
  const diameters = new Set(runs.map((run) => run.diameterInches ?? null));
  if (materials.size > 1) return 'transition_coupling';
  if (diameters.size > 1) return 'reducing_coupling';
  if (runs.length >= 3) {
    if (system === 'sanitary' || system === 'vent') return 'wye';
    return 'tee';
  }
  return 'coupling';
}

function ensureAutoNode(params: {
  nodes: PlumbingNode[];
  point: PlumbingPoint3D;
  system: PlumbingRunSystem;
  label: string;
}): { nodes: PlumbingNode[]; nodeId: string } {
  const existing = params.nodes.find((node) => node.system === params.system && pointsNearlyEqual(node.position, params.point));
  if (existing) return { nodes: params.nodes, nodeId: existing.id };
  const node: PlumbingNode = {
    id: createId('plumbing-auto-fitting-node'),
    kind: params.label.toLowerCase().includes('wye') ? 'wye' : 'fitting',
    system: params.system,
    position: params.point,
    label: params.label,
  };
  return { nodes: [...params.nodes, node], nodeId: node.id };
}

function makeFitting(params: {
  type: PlumbingFittingType;
  system: PlumbingRunSystem;
  nodeId: string;
  connectedRunIds: string[];
  diameterInches: number | null;
  secondaryDiameterInches?: number | null;
  material: PlumbingMaterial;
  schedule?: PlumbingRun['schedule'];
  elevationMode: PlumbingElevationMode;
  rotationRad?: number;
}): PlumbingFitting {
  return {
    id: createId(`plumbing-fitting-${params.type}`),
    type: params.type,
    system: params.system,
    nodeId: params.nodeId,
    connectedRunIds: params.connectedRunIds,
    diameterInches: params.diameterInches,
    secondaryDiameterInches: params.secondaryDiameterInches,
    material: params.material,
    schedule: params.schedule,
    rotationRad: params.rotationRad ?? 0,
    elevationMode: params.elevationMode,
    labelVisible: true,
    isAutoGenerated: true,
  };
}

export function reconcileAutoGeneratedPlumbingFittings(system: PlumbingSystem): PlumbingSystem {
  const manualFittings = (system.fittings ?? []).filter((fitting) => !fitting.isAutoGenerated);
  let nodes = [...system.nodes];
  const autoFittings: PlumbingFitting[] = [];

  system.runs.forEach((run) => {
    for (let index = 1; index < run.path.length - 1; index += 1) {
      const previous = run.path[index - 1];
      const current = run.path[index];
      const next = run.path[index + 1];
      if (!previous || !current || !next) continue;
      const type = fittingForBend(run.system, angleBetween(previous, current, next));
      const definition = fittingDefinition(type);
      const ensured = ensureAutoNode({
        nodes,
        point: current,
        system: run.system,
        label: definition?.label ?? 'Pipe fitting',
      });
      nodes = ensured.nodes;
      autoFittings.push(makeFitting({
        type,
        system: run.system,
        nodeId: ensured.nodeId,
        connectedRunIds: [run.id],
        diameterInches: run.diameterInches,
        material: run.material,
        schedule: run.schedule,
        elevationMode: run.elevationMode,
      }));
    }
  });

  nodes.forEach((node) => {
    const connectedRuns = system.runs.filter((run) => run.startNodeId === node.id || run.endNodeId === node.id);
    if (connectedRuns.length < 2) return;
    const type = fittingForConnectedRuns(connectedRuns);
    const primaryRun = primaryRunAtNode(connectedRuns, node.id);
    if (!primaryRun) return;
    autoFittings.push(makeFitting({
      type,
      system: primaryRun.system,
      nodeId: node.id,
      connectedRunIds: connectedRuns.map((run) => run.id),
      diameterInches: primaryRun.diameterInches,
      secondaryDiameterInches: connectedRuns.find((run) => run.diameterInches !== primaryRun.diameterInches)?.diameterInches,
      material: primaryRun.material,
      schedule: primaryRun.schedule,
      elevationMode: primaryRun.elevationMode,
    }));
  });

  return {
    ...system,
    nodes,
    fittings: [...manualFittings, ...autoFittings],
  };
}
