import { defaultPipeScheduleForMaterial } from '../plumbingDefaults';
import { defaultStockLengthForPipe } from './plumbingStockLengths';
import { getPlumbingFixtureRoughInDefault } from './plumbingFixtureRoughIns';
import { ipc2024MinimumDrainageSlopeInPerFt } from './ipcDrainageSlope';
import type { PlumbingFitting, PlumbingFittingType } from '../plumbingFittingTypes';
import type {
  PlumbingFixture,
  PlumbingFixtureRoughInAssembly,
  PlumbingMaterial,
  PlumbingNode,
  PlumbingPoint3D,
  PlumbingRoughInSystem,
  PlumbingRun,
  PlumbingSystem,
} from '../plumbingTypes';

export type PlumbingFixtureRoughInGenerationResult = {
  system: PlumbingSystem;
  roughIn: PlumbingFixtureRoughInAssembly | null;
  message: string;
};

export type PlumbingFixtureRoughInGenerationParams = {
  system: PlumbingSystem;
  fixtureId: string;
  mainRunId: string;
  tapPoint: PlumbingPoint3D;
  segmentIndex?: number;
};

function roughInId(fixtureId: string, system: PlumbingRoughInSystem): string {
  return `plumbing-rough-in-${fixtureId}-${system}`;
}

function roughInPartId(fixtureId: string, system: PlumbingRoughInSystem, part: string): string {
  return `${roughInId(fixtureId, system)}-${part}`;
}

function pointsNearlyEqual(a: PlumbingPoint3D, b: PlumbingPoint3D): boolean {
  return Math.hypot(a.x - b.x, a.z - b.z) <= 0.025;
}

function clonePoint(point: PlumbingPoint3D): PlumbingPoint3D {
  return { x: point.x, y: point.y, z: point.z };
}

function pointWithElevation(point: PlumbingPoint3D, y: number): PlumbingPoint3D {
  return { x: point.x, y, z: point.z };
}

function pipeRun(params: {
  id: string;
  system: PlumbingRoughInSystem;
  startNodeId: string;
  endNodeId: string;
  path: PlumbingPoint3D[];
  diameterInches: number | null;
  material: PlumbingMaterial;
  schedule?: PlumbingRun['schedule'];
  elevationMode: PlumbingRun['elevationMode'];
  slopeInPerFt?: number;
  labelVisible?: boolean;
}): PlumbingRun {
  const stock = defaultStockLengthForPipe({ material: params.material, system: params.system });
  return {
    id: params.id,
    system: params.system,
    startNodeId: params.startNodeId,
    endNodeId: params.endNodeId,
    path: params.path.map(clonePoint),
    diameterInches: params.diameterInches,
    material: params.material,
    schedule: params.schedule ?? defaultPipeScheduleForMaterial(params.material),
    stockLengthFt: stock.stockLengthFt,
    stockLengthPreset: stock.stockLengthPreset,
    stockLengthKind: stock.stockLengthKind,
    slopeInPerFt: params.system === 'sanitary'
      ? params.slopeInPerFt ?? ipc2024MinimumDrainageSlopeInPerFt(params.diameterInches)
      : undefined,
    elevationMode: params.elevationMode,
    labelVisible: params.labelVisible ?? true,
  };
}

function fitting(params: {
  id: string;
  type: PlumbingFittingType;
  system: PlumbingRoughInSystem;
  nodeId: string;
  connectedRunIds: string[];
  diameterInches: number | null;
  secondaryDiameterInches?: number | null;
  material: PlumbingMaterial;
  schedule?: PlumbingRun['schedule'];
  elevationMode: PlumbingRun['elevationMode'];
}): PlumbingFitting {
  return {
    id: params.id,
    type: params.type,
    system: params.system,
    nodeId: params.nodeId,
    connectedRunIds: params.connectedRunIds,
    diameterInches: params.diameterInches,
    secondaryDiameterInches: params.secondaryDiameterInches,
    material: params.material,
    schedule: params.schedule,
    rotationRad: 0,
    elevationMode: params.elevationMode,
    labelVisible: true,
    isAutoGenerated: true,
  };
}

function removeOwnedRoughInParts(system: PlumbingSystem, fixtureId: string, roughInSystem: PlumbingRoughInSystem): PlumbingSystem {
  const existing = system.roughIns.find((roughIn) => roughIn.fixtureId === fixtureId && roughIn.system === roughInSystem);
  if (!existing) return system;
  const removableRunIds = new Set([
    existing.branchRunId,
    existing.riserRunId,
    existing.trapArmRunId,
  ].filter((id): id is string => Boolean(id)));
  const removableNodeIds = new Set([
    existing.riserBottomNodeId,
    existing.riserTopNodeId,
  ]);
  const removableFittingIds = new Set(existing.fittingIds);
  return {
    ...system,
    roughIns: system.roughIns.filter((roughIn) => roughIn.id !== existing.id),
    nodes: system.nodes.filter((node) => !removableNodeIds.has(node.id)),
    runs: system.runs.filter((run) => !removableRunIds.has(run.id)),
    fittings: (system.fittings ?? []).filter((item) => !removableFittingIds.has(item.id)),
  };
}

function resolveFixtureNode(fixture: PlumbingFixture, system: PlumbingRoughInSystem, nodes: readonly PlumbingNode[]): PlumbingNode | null {
  const nodeIds = fixture.connectionNodeIds[system] ?? [];
  for (const nodeId of nodeIds) {
    const node = nodes.find((candidate) => candidate.id === nodeId);
    if (node) return node;
  }
  return null;
}

function splitMainRunAtTap(params: {
  system: PlumbingSystem;
  mainRun: PlumbingRun;
  tapPoint: PlumbingPoint3D;
  tapNode: PlumbingNode;
  segmentIndex?: number;
}): { system: PlumbingSystem; tapNodeId: string; mainRunIds: string[] } {
  const connectedMainRunIds = (nodeId: string): string[] => {
    const ids = params.system.runs
      .filter((run) =>
        run.system === params.mainRun.system &&
        (run.startNodeId === nodeId || run.endNodeId === nodeId),
      )
      .map((run) => run.id);
    return ids.length > 0 ? ids : [params.mainRun.id];
  };
  const startNode = params.system.nodes.find((node) => node.id === params.mainRun.startNodeId);
  const endNode = params.system.nodes.find((node) => node.id === params.mainRun.endNodeId);
  if (startNode && pointsNearlyEqual(startNode.position, params.tapPoint)) {
    return { system: params.system, tapNodeId: startNode.id, mainRunIds: connectedMainRunIds(startNode.id) };
  }
  if (endNode && pointsNearlyEqual(endNode.position, params.tapPoint)) {
    return { system: params.system, tapNodeId: endNode.id, mainRunIds: connectedMainRunIds(endNode.id) };
  }
  const existing = params.system.nodes.find((node) => node.system === params.mainRun.system && pointsNearlyEqual(node.position, params.tapPoint));
  if (existing) {
    return { system: params.system, tapNodeId: existing.id, mainRunIds: connectedMainRunIds(existing.id) };
  }
  const segmentIndex = Math.max(1, Math.min(params.segmentIndex ?? 1, params.mainRun.path.length - 1));
  const firstPath = [...params.mainRun.path.slice(0, segmentIndex), params.tapPoint];
  const secondPath = [params.tapPoint, ...params.mainRun.path.slice(segmentIndex)];
  const downstreamRunId = `${params.mainRun.id}-${params.tapNode.id}-downstream`;
  const firstRun: PlumbingRun = {
    ...params.mainRun,
    path: firstPath,
    endNodeId: params.tapNode.id,
  };
  const secondRun: PlumbingRun = {
    ...params.mainRun,
    id: downstreamRunId,
    path: secondPath,
    startNodeId: params.tapNode.id,
  };
  return {
    system: {
      ...params.system,
      nodes: [...params.system.nodes, params.tapNode],
      runs: params.system.runs.flatMap((run) => (run.id === params.mainRun.id ? [firstRun, secondRun] : [run])),
    },
    tapNodeId: params.tapNode.id,
    mainRunIds: [firstRun.id, secondRun.id],
  };
}

function tapFittingType(system: PlumbingRoughInSystem): PlumbingFittingType {
  if (system === 'sanitary' || system === 'vent') return 'wye';
  return 'tee';
}

function tapFittingMainDiameter(params: {
  system: PlumbingRoughInSystem;
  mainRun: PlumbingRun;
  branchDiameterInches: number | null;
}): number | null {
  if (params.system !== 'sanitary' && params.system !== 'vent') return params.branchDiameterInches;
  return params.mainRun.diameterInches ?? params.branchDiameterInches;
}

function branchElevationMode(system: PlumbingRoughInSystem): PlumbingRun['elevationMode'] {
  if (system === 'sanitary') return 'under_slab';
  if (system === 'vent') return 'in_wall';
  return 'in_wall';
}

export function createOrReplaceFixtureRoughInAssembly(
  params: PlumbingFixtureRoughInGenerationParams,
): PlumbingFixtureRoughInGenerationResult {
  const fixture = params.system.fixtures.find((item) => item.id === params.fixtureId);
  if (!fixture) return { system: params.system, roughIn: null, message: 'Fixture not found.' };
  const mainRun = params.system.runs.find((run) => run.id === params.mainRunId);
  if (!mainRun) return { system: params.system, roughIn: null, message: 'Main run not found.' };
  const roughInSystem = mainRun.system as PlumbingRoughInSystem;
  const fixtureNode = resolveFixtureNode(fixture, roughInSystem, params.system.nodes);
  if (!fixtureNode) {
    return { system: params.system, roughIn: null, message: `${fixture.mark} does not have a ${roughInSystem.replace('_', ' ')} connection node.` };
  }
  const defaults = getPlumbingFixtureRoughInDefault({ fixture, system: roughInSystem });
  if (!defaults) {
    return { system: params.system, roughIn: null, message: `${fixture.mark} does not support ${roughInSystem.replace('_', ' ')} rough-ins.` };
  }

  const baseSystem = removeOwnedRoughInParts(params.system, fixture.id, roughInSystem);
  const idBase = roughInId(fixture.id, roughInSystem);
  const tapNode: PlumbingNode = {
    id: roughInPartId(fixture.id, roughInSystem, 'tap-node'),
    kind: 'run_tap',
    system: roughInSystem,
    position: pointWithElevation(params.tapPoint, defaults.branchElevationM),
    label: roughInSystem === 'sanitary' ? 'Sanitary tap' : `${roughInSystem.replace('_', ' ')} tap`,
  };
  const split = splitMainRunAtTap({
    system: baseSystem,
    mainRun,
    tapPoint: pointWithElevation(params.tapPoint, defaults.branchElevationM),
    tapNode,
    segmentIndex: params.segmentIndex,
  });
  const actualTapNode = split.system.nodes.find((node) => node.id === split.tapNodeId) ?? tapNode;

  const bottomNodeId = roughInPartId(fixture.id, roughInSystem, 'riser-bottom');
  const topNodeId = roughInPartId(fixture.id, roughInSystem, 'riser-top');
  const branchRunId = roughInPartId(fixture.id, roughInSystem, 'branch-run');
  const riserRunId = roughInPartId(fixture.id, roughInSystem, 'riser-run');
  const branchPoint = pointWithElevation(fixtureNode.position, defaults.branchElevationM);
  const topPoint = pointWithElevation(fixtureNode.position, defaults.topElevationM);
  const bottomNode: PlumbingNode = {
    id: bottomNodeId,
    kind: 'riser_bottom',
    system: roughInSystem,
    position: branchPoint,
    fixtureId: fixture.id,
    label: `${fixture.mark} rough-in bottom`,
  };
  const topNode: PlumbingNode = {
    id: topNodeId,
    kind: 'riser_top',
    system: roughInSystem,
    position: topPoint,
    fixtureId: fixture.id,
    label: `${fixture.mark} rough-in top`,
  };
  const branchRun = pipeRun({
    id: branchRunId,
    system: roughInSystem,
    startNodeId: roughInSystem === 'sanitary' ? bottomNodeId : actualTapNode.id,
    endNodeId: roughInSystem === 'sanitary' ? actualTapNode.id : bottomNodeId,
    path: roughInSystem === 'sanitary'
      ? [branchPoint, actualTapNode.position]
      : [actualTapNode.position, branchPoint],
    diameterInches: defaults.diameterInches,
    material: defaults.material,
    schedule: defaults.schedule,
    elevationMode: branchElevationMode(roughInSystem),
    slopeInPerFt: roughInSystem === 'sanitary'
      ? mainRun.slopeInPerFt ?? ipc2024MinimumDrainageSlopeInPerFt(defaults.diameterInches)
      : undefined,
  });
  const riserRun = pipeRun({
    id: riserRunId,
    system: roughInSystem,
    startNodeId: bottomNodeId,
    endNodeId: topNodeId,
    path: [branchPoint, topPoint],
    diameterInches: defaults.diameterInches,
    material: defaults.material,
    schedule: defaults.schedule,
    elevationMode: 'vertical',
    slopeInPerFt: undefined,
  });
  const fittingIds: string[] = [];
  const tapFittingId = roughInPartId(fixture.id, roughInSystem, 'tap-fitting');
  fittingIds.push(tapFittingId);
  const generatedFittings: PlumbingFitting[] = [
    fitting({
      id: tapFittingId,
      type: tapFittingType(roughInSystem),
      system: roughInSystem,
      nodeId: actualTapNode.id,
      connectedRunIds: [...split.mainRunIds, branchRunId],
      diameterInches: tapFittingMainDiameter({
        system: roughInSystem,
        mainRun,
        branchDiameterInches: defaults.diameterInches,
      }),
      secondaryDiameterInches:
        (roughInSystem === 'sanitary' || roughInSystem === 'vent') &&
        mainRun.diameterInches != null &&
        defaults.diameterInches != null &&
        mainRun.diameterInches !== defaults.diameterInches
          ? defaults.diameterInches
          : undefined,
      material: defaults.material,
      schedule: defaults.schedule,
      elevationMode: branchRun.elevationMode,
    }),
  ];
  defaults.fittingTypes.forEach((type, index) => {
    const id = roughInPartId(fixture.id, roughInSystem, `fixture-fitting-${index + 1}-${type}`);
    fittingIds.push(id);
    generatedFittings.push(fitting({
      id,
      type,
      system: roughInSystem,
      nodeId: type === 'closet_bend' || type === 'p_trap' ? bottomNodeId : topNodeId,
      connectedRunIds: [riserRunId, branchRunId],
      diameterInches: defaults.diameterInches,
      material: defaults.material,
      schedule: defaults.schedule,
      elevationMode: type === 'closet_bend' || type === 'p_trap' ? branchRun.elevationMode : 'vertical',
    }));
  });

  const roughIn: PlumbingFixtureRoughInAssembly = {
    id: idBase,
    fixtureId: fixture.id,
    system: roughInSystem,
    mainRunId: params.mainRunId,
    tapNodeId: actualTapNode.id,
    fixtureNodeId: fixtureNode.id,
    riserBottomNodeId: bottomNodeId,
    riserTopNodeId: topNodeId,
    branchRunId,
    riserRunId,
    fittingIds,
    diameterInches: defaults.diameterInches,
    material: defaults.material,
    schedule: defaults.schedule,
    elevationMode: 'vertical',
    riserKind: defaults.riserKind,
    labelVisible: true,
    isAutoGenerated: true,
  };

  return {
    system: {
      ...split.system,
      nodes: [...split.system.nodes, bottomNode, topNode],
      runs: [...split.system.runs, branchRun, riserRun],
      fittings: [...(split.system.fittings ?? []), ...generatedFittings],
      roughIns: [...split.system.roughIns, roughIn],
    },
    roughIn,
    message: `${fixture.mark} ${roughInSystem.replace('_', ' ')} rough-in created.`,
  };
}
