import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { savePDFWithPlatformSupport } from '../../../utils/pdf';
import { sanitizeEstimateExportFileStem } from '../importExport/estimateExportBuilder';
import type { BuildGanttScheduleResult, GanttActivity } from '../schedule/buildGanttSchedule';
import type { ScheduleActivity } from '../scheduling/adapters/estimateLineItemsToScheduleActivities';
import { isDisplayCritical } from '../scheduling/cpm/cpmDisplayCritical';
import type { CpmResult, ResourceHistogramDay, ScheduleSettings } from '../scheduling/cpmTypes';

declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: Record<string, unknown>) => jsPDF;
    lastAutoTable: { finalY: number };
  }
}

const MARGIN = 14;
const FOOTER_HEIGHT = 10;
const ROWS_PER_CHART_PAGE = 18;
const CHART_LABEL_WIDTH = 72;
const CHART_META_WIDTH = 48;
const CHART_BAR_AREA_WIDTH = 145;

export interface BuildGanttPdfDocumentParams {
  schedule: BuildGanttScheduleResult | null;
  projectName: string;
  estimateType: string;
  exportedAt?: Date;
  /** Optional CPM data for Level III Gantt export. */
  cpmResult?: CpmResult | null;
  activities?: ScheduleActivity[];
  scheduleSettings?: ScheduleSettings;
  leveledOffsets?: Record<string, number>;
  resourceHistogram?: ResourceHistogramDay[];
}

function formatExportDate(date: Date): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

function addFooter(doc: jsPDF): void {
  const pageCount = doc.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(120, 120, 120);
    doc.text('Generated by Concrete Calc', pageWidth / 2, pageHeight - 5, { align: 'center' });
  }
}

function drawHeader(
  doc: jsPDF,
  params: BuildGanttPdfDocumentParams,
  pageWidth: number,
  y: number,
  subtitle?: string,
): number {
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(20, 20, 20);
  doc.text('Gantt Schedule Export', MARGIN, y);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(60, 60, 60);
  const exportedAt = params.exportedAt ?? new Date();
  const lines = [
    `Project: ${params.projectName}`,
    `Estimate type: ${params.estimateType}`,
    `Export date: ${formatExportDate(exportedAt)}`,
    ...(params.schedule
      ? [
          `Activities: ${params.schedule.activities.length}`,
          `Planned duration: ${params.schedule.plannedDurationDays} days`,
        ]
      : params.cpmResult
        ? [
            `Activities: ${params.cpmResult.activities.length}`,
            `Project duration: ${params.cpmResult.projectDurationDays} days`,
          ]
        : []),
  ];
  if (subtitle) lines.push(subtitle);

  let currentY = y + 8;
  for (const line of lines) {
    doc.text(line, MARGIN, currentY);
    currentY += 5;
  }

  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, currentY + 2, pageWidth - MARGIN, currentY + 2);

  return currentY + 8;
}

function getTimelineBounds(activities: GanttActivity[]): { minDate: string; maxDate: string } {
  let minDate = activities[0]?.plannedStart ?? '';
  let maxDate = activities[0]?.plannedFinish ?? '';

  for (const activity of activities) {
    if (activity.plannedStart < minDate) minDate = activity.plannedStart;
    if (activity.plannedFinish > maxDate) maxDate = activity.plannedFinish;
  }

  return { minDate, maxDate };
}

function dateToOffset(date: string, minDate: string): number {
  const min = Date.parse(`${minDate}T00:00:00Z`);
  const current = Date.parse(`${date}T00:00:00Z`);
  if (!Number.isFinite(min) || !Number.isFinite(current)) return 0;
  return Math.max(0, Math.round((current - min) / 86_400_000));
}

function drawGanttChartPage(
  doc: jsPDF,
  activities: GanttActivity[],
  pageWidth: number,
  startY: number,
  pageIndex: number,
  totalPages: number,
): number {
  const pageHeight = doc.internal.pageSize.getHeight();
  const { minDate, maxDate } = getTimelineBounds(activities);
  const totalSpan = Math.max(1, dateToOffset(maxDate, minDate) + 1);
  const barX = MARGIN + CHART_LABEL_WIDTH + CHART_META_WIDTH;
  const barWidth = Math.min(CHART_BAR_AREA_WIDTH, pageWidth - barX - MARGIN);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(80, 80, 80);
  doc.text('Code / Title', MARGIN, startY);
  doc.text('Dur', MARGIN + CHART_LABEL_WIDTH, startY);
  doc.text('Start / Finish', MARGIN + CHART_LABEL_WIDTH + 14, startY);
  doc.text('Timeline', barX, startY);

  let y = startY + 4;
  doc.setDrawColor(220, 220, 220);
  doc.line(MARGIN, y, pageWidth - MARGIN, y);
  y += 5;

  const pageActivities = activities.slice(
    pageIndex * ROWS_PER_CHART_PAGE,
    (pageIndex + 1) * ROWS_PER_CHART_PAGE,
  );

  for (const activity of pageActivities) {
    if (y > pageHeight - MARGIN - FOOTER_HEIGHT - 8) break;

    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 30, 30);
    doc.text(activity.activityCode, MARGIN, y);

    doc.setFont('helvetica', 'normal');
    const titleLines = doc.splitTextToSize(activity.title, CHART_LABEL_WIDTH - 14);
    doc.text(titleLines.slice(0, 2), MARGIN + 14, y);

    doc.text(`${activity.durationDays}d`, MARGIN + CHART_LABEL_WIDTH, y);
    doc.text(activity.plannedStart, MARGIN + CHART_LABEL_WIDTH + 14, y);
    doc.text(activity.plannedFinish, MARGIN + CHART_LABEL_WIDTH + 14, y + 3.5);

    const startOffset = dateToOffset(activity.plannedStart, minDate);
    const endOffset = dateToOffset(activity.plannedFinish, minDate);
    const left = barX + (startOffset / totalSpan) * barWidth;
    const width = Math.max(2, ((endOffset - startOffset + 1) / totalSpan) * barWidth);

    doc.setFillColor(90, 90, 90);
    doc.rect(left, y - 3, width, 4, 'F');

    y += Math.max(8, titleLines.length > 1 ? 10 : 8);
  }

  if (totalPages > 1) {
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 120);
    doc.text(`Chart page ${pageIndex + 1} of ${totalPages}`, pageWidth - MARGIN, startY - 2, {
      align: 'right',
    });
  }

  return y;
}

function drawGanttChart(doc: jsPDF, params: BuildGanttPdfDocumentParams): void {
  const activities = params.schedule.activities;
  if (activities.length === 0) return;

  const pageWidth = doc.internal.pageSize.getWidth();
  const totalPages = Math.max(1, Math.ceil(activities.length / ROWS_PER_CHART_PAGE));

  for (let pageIndex = 0; pageIndex < totalPages; pageIndex += 1) {
    if (pageIndex > 0) doc.addPage();
    const startY = drawHeader(
      doc,
      params,
      pageWidth,
      MARGIN,
      pageIndex === 0 ? 'Gantt chart' : 'Gantt chart (continued)',
    );
    drawGanttChartPage(doc, activities, pageWidth, startY, pageIndex, totalPages);
  }
}

function drawLogicTable(doc: jsPDF, params: BuildGanttPdfDocumentParams): void {
  doc.addPage();
  const pageWidth = doc.internal.pageSize.getWidth();
  const startY = drawHeader(doc, params, pageWidth, MARGIN, 'Logic network');

  doc.autoTable({
    startY: startY,
    head: [['Code', 'Title', 'Predecessor', 'Relationship', 'Lag', 'Duration']],
    body: params.schedule.activities.map((activity) => [
      activity.activityCode,
      activity.title,
      activity.predecessorActivityCode ?? '',
      activity.relationshipType,
      String(activity.lagDays),
      `${activity.durationDays}d`,
    ]),
    margin: { left: MARGIN, right: MARGIN },
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [70, 70, 70], textColor: 255 },
    alternateRowStyles: { fillColor: [245, 245, 245] },
  });
}

function drawCpmTable(doc: jsPDF, params: BuildGanttPdfDocumentParams): void {
  if (!params.cpmResult || !params.activities) return;
  const cpmByCode = new Map(params.cpmResult.activities.map((a) => [a.activityCode, a]));
  const actByCode = new Map(params.activities.map((a) => [a.activityCode, a]));
  const sorted = [...params.cpmResult.activities].sort(
    (left, right) => left.earlyStart - right.earlyStart,
  );

  doc.addPage();
  const pageWidth = doc.internal.pageSize.getWidth();
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('CPM Schedule Table', MARGIN, 20);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text(`Project: ${params.projectName}`, MARGIN, 27);

  doc.autoTable({
    startY: 32,
    head: [['Code', 'Description', 'Dur', 'ES', 'EF', 'LS', 'LF', 'TF', 'FF', 'Critical']],
    body: sorted.map((cpm) => {
      const act = actByCode.get(cpm.activityCode);
      return [
        cpm.activityCode,
        act?.activityDescription ?? '',
        String(act?.durationDays ?? ''),
        String(cpm.earlyStart),
        String(cpm.earlyFinish),
        String(cpm.lateStart),
        String(cpm.lateFinish),
        String(cpm.totalFloat),
        String(cpm.freeFloat),
        isDisplayCritical(params.cpmResult, cpm.activityCode) ? 'Yes' : '',
      ];
    }),
    margin: { left: MARGIN, right: MARGIN },
    styles: { fontSize: 7, cellPadding: 2 },
    headStyles: { fillColor: [70, 70, 70], textColor: 255 },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    didParseCell: (data: {
      section: string;
      column: { index: number };
      row: { index: number };
      cell: { styles: { fillColor: number[] | string; textColor: number | number[] } };
    }) => {
      if (data.section === 'body' && data.column.index === 9) {
        const cpm = sorted[data.row.index];
        if (cpm && isDisplayCritical(params.cpmResult!, cpm.activityCode)) {
          data.cell.styles.fillColor = [255, 220, 220];
          data.cell.styles.textColor = [200, 0, 0];
        }
      }
    },
  });
  void pageWidth;
}

export function buildGanttPdfDocument(params: BuildGanttPdfDocumentParams): jsPDF {
  const doc = new jsPDF({ unit: 'mm', format: 'letter', orientation: 'landscape' });
  if (params.schedule) {
    drawGanttChart(doc, params as BuildGanttPdfDocumentParams & { schedule: BuildGanttScheduleResult });
    drawLogicTable(doc, params as BuildGanttPdfDocumentParams & { schedule: BuildGanttScheduleResult });
  }
  if (params.cpmResult) {
    drawCpmTable(doc, params);
  }
  addFooter(doc);
  return doc;
}

export function buildGanttPdfFileName(projectName: string, date = new Date()): string {
  const stem = sanitizeEstimateExportFileStem(projectName);
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${stem}-gantt-${year}-${month}-${day}.pdf`;
}

export async function downloadGanttPdf(
  params: BuildGanttPdfDocumentParams & { fileName?: string },
): Promise<void> {
  const doc = buildGanttPdfDocument(params);
  const fileName = params.fileName ?? buildGanttPdfFileName(params.projectName);
  await savePDFWithPlatformSupport(doc, fileName, 'Gantt Schedule');
}
