import type { DocumentQuestion } from '../../types';

/**
 * RFI Pack question bank for the Document Builder intake form.
 * Answer keys align with `rfiPreviewAdapter` and `RfiDocument` renderer.
 */
export const rfiQuestions: DocumentQuestion[] = [
  {
    questionKey: 'rfiNumber',
    label: 'RFI Number',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'quick',
    helperText: 'Auto-assigned on save if left blank (e.g. RFI-001). You can enter a custom number.',
  },
  {
    questionKey: 'rfiTitle',
    label: 'RFI title',
    type: 'text',
    group: 'scope',
    required: true,
    mode: 'quick',
  },
  {
    questionKey: 'question',
    label: 'Question',
    type: 'text',
    group: 'scope',
    required: true,
    mode: 'quick',
  },
  {
    questionKey: 'drawingSpecReference',
    label: 'Drawing / spec reference',
    type: 'text',
    group: 'scope',
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'submittedBy',
    label: 'Submitted by',
    type: 'text',
    group: 'parties',
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'submittedTo',
    label: 'Submitted to',
    type: 'text',
    group: 'parties',
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'dueDate',
    label: 'Due date',
    type: 'text',
    group: 'schedule',
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'costImpact',
    label: 'Cost impact',
    type: 'text',
    group: 'change_management',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'scheduleImpact',
    label: 'Schedule impact',
    type: 'text',
    group: 'change_management',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'response',
    label: 'Response',
    type: 'text',
    group: 'execution',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'respondedBy',
    label: 'Responded by',
    type: 'text',
    group: 'execution',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'responseDate',
    label: 'Response date',
    type: 'text',
    group: 'execution',
    required: false,
    mode: 'standard',
  },
  {
    questionKey: 'status',
    label: 'Status',
    type: 'select',
    group: 'execution',
    options: [
      { value: 'Draft', label: 'Draft' },
      { value: 'Submitted', label: 'Submitted' },
      { value: 'Under Review', label: 'Under Review' },
      { value: 'Answered', label: 'Answered' },
      { value: 'Closed', label: 'Closed' },
      { value: 'Void', label: 'Void' },
    ],
    required: false,
    mode: 'quick',
  },
  {
    questionKey: 'attachmentDrawings',
    label: 'Drawings (references)',
    type: 'text',
    group: 'execution',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'attachmentPhotos',
    label: 'Photos (references)',
    type: 'text',
    group: 'execution',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'attachmentSpecSections',
    label: 'Spec sections (references)',
    type: 'text',
    group: 'execution',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'attachmentOtherReferences',
    label: 'Other references',
    type: 'text',
    group: 'execution',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'reviewedBy',
    label: 'Reviewed by',
    type: 'text',
    group: 'execution',
    required: false,
    mode: 'advanced',
  },
  {
    questionKey: 'signatureDate',
    label: 'Signature date',
    type: 'text',
    group: 'execution',
    required: false,
    mode: 'advanced',
  },
];
