import * as THREE from 'three';
import { describe, expect, it } from 'vitest';
import {
  addFixtureToPlumbingSystem,
  addCmuSepticTankToPlumbingSystem,
  addRunToPlumbingSystem,
  createOrReplaceFixtureRoughInAssembly,
  createDefaultPlumbingSystem,
  validatePlumbingSystem,
  type PlumbingFitting,
  type PlumbingNode,
  type PlumbingRun,
  type PlumbingSystem,
} from '../plumbing';
import { buildDesignBuilderViewerPlumbingScene } from '../plumbing/three/DesignBuilderViewerPlumbingScene';
import { createPipeTubeMesh } from '../plumbing/three/createPipeTubeMesh';
import { createPlumbingRiserMesh } from '../plumbing/three/createPlumbingRiserMesh';
import { createProceduralPlumbingEquipmentMesh } from '../plumbing/three/createProceduralPlumbingEquipmentMesh';
import { createProceduralPlumbingFittingMesh } from '../plumbing/three/createProceduralPlumbingFittingMesh';
import { createProceduralPlumbingFixtureMesh } from '../plumbing/three/createProceduralPlumbingFixtureMesh';
import { createPlumbingThreeMaterials } from '../plumbing/three/plumbingThreeMaterials';
import {
  defaultPlumbingElevationDefaults,
  resolvePlumbingRunPath,
} from '../plumbing/three/plumbingElevationResolver';
import {
  fittingSocketLengthMeters,
  getConnectedRunDirectionsAtNode,
  groupObjectNames,
  alignObjectPortToWorldPoint,
  placeObjectBaseAtY,
  type ConnectorPort,
} from '../plumbing/three/plumbingThreeUtils';
import { resolveSelectableDataForObject } from '../ui/DesignBuilderViewerPicking';
import { createDesignBuilderViewerSceneRegistry } from '../ui/DesignBuilderViewerSceneRegistry';

function baseNodes(system: PlumbingRun['system']): PlumbingNode[] {
  return [
    {
      id: 'node-a',
      kind: 'fixture_connection',
      system,
      position: { x: 1, y: 0, z: 2 },
      label: 'A',
    },
    {
      id: 'node-b',
      kind: 'fixture_connection',
      system,
      position: { x: 4, y: 0, z: 2 },
      label: 'B',
    },
  ];
}

function run(system: PlumbingRun['system'], patch: Partial<PlumbingRun> = {}): PlumbingRun {
  return {
    id: `run-${system}`,
    system,
    startNodeId: 'node-a',
    endNodeId: 'node-b',
    path: [
      { x: 1, y: 0, z: 2 },
      { x: 2.5, y: 0, z: 3 },
      { x: 4, y: 0, z: 2 },
    ],
    diameterInches: system === 'sanitary' ? 3 : 0.5,
    material: system === 'sanitary' || system === 'vent' ? 'pvc' : 'pex',
    schedule: system === 'sanitary' || system === 'vent' ? 'SCH 40' : 'N/A',
    stockLengthFt: 10,
    stockLengthPreset: '10ft',
    stockLengthKind: 'stick',
    slopeInPerFt: system === 'sanitary' ? 0.25 : undefined,
    elevationMode: system === 'sanitary' ? 'under_slab' : 'in_wall',
    labelVisible: true,
    ...patch,
  };
}

function plumbingSystemWithRun(plumbingRun: PlumbingRun): PlumbingSystem {
  return {
    ...createDefaultPlumbingSystem(),
    nodes: baseNodes(plumbingRun.system),
    runs: [plumbingRun],
  };
}

function fitting(type: PlumbingFitting['type'], patch: Partial<PlumbingFitting> = {}): PlumbingFitting {
  return {
    id: `fitting-${type}`,
    type,
    system: 'sanitary',
    nodeId: 'node-a',
    connectedRunIds: ['run-sanitary'],
    diameterInches: 3,
    material: 'pvc',
    schedule: 'SCH 40',
    rotationRad: 0,
    elevationMode: 'under_slab',
    labelVisible: true,
    isAutoGenerated: false,
    ...patch,
  };
}

function groupHasSphereGeometry(group: THREE.Object3D): boolean {
  let hasSphere = false;
  group.traverse((object) => {
    if (object instanceof THREE.Mesh && object.geometry.type === 'SphereGeometry') {
      hasSphere = true;
    }
  });
  return hasSphere;
}

function objectBounds(object: THREE.Object3D): THREE.Box3 {
  object.updateMatrixWorld(true);
  return new THREE.Box3().setFromObject(object);
}

function meshByName(group: THREE.Object3D, name: string): THREE.Mesh {
  let found: THREE.Mesh | null = null;
  group.traverse((object) => {
    if (object.name === name && object instanceof THREE.Mesh) found = object;
  });
  expect(found).toBeTruthy();
  return found!;
}

function lineByName(group: THREE.Object3D, name: string): THREE.Line {
  let found: THREE.Line | null = null;
  group.traverse((object) => {
    if (object.name === name && object instanceof THREE.Line) found = object;
  });
  expect(found).toBeTruthy();
  return found!;
}

function cylinderAxis(mesh: THREE.Mesh): THREE.Vector3 {
  return new THREE.Vector3(0, 1, 0).applyQuaternion(mesh.quaternion).normalize();
}

function cylinderEndpoints(mesh: THREE.Mesh): [THREE.Vector3, THREE.Vector3] {
  const height = (mesh.geometry as THREE.CylinderGeometry).parameters.height as number;
  const axis = cylinderAxis(mesh);
  return [
    mesh.position.clone().addScaledVector(axis, -height / 2),
    mesh.position.clone().addScaledVector(axis, height / 2),
  ];
}

describe('Design Builder procedural plumbing 3D', () => {
  it('resolves 2D plan points to 3D X/Z and under-slab sanitary slope', () => {
    const sanitary = run('sanitary');
    const resolved = resolvePlumbingRunPath({
      system: plumbingSystemWithRun(sanitary),
      run: sanitary,
    });

    expect(resolved.points).toHaveLength(3);
    expect(resolved.points[0]).toMatchObject({ x: 1, z: 2 });
    expect(resolved.points[1]).toMatchObject({ x: 2.5, z: 3 });
    expect(resolved.points[0]!.y).toBeLessThan(defaultPlumbingElevationDefaults.slabTopElevationM);
    expect(resolved.points[2]!.y).toBeLessThan(resolved.points[0]!.y);
  });

  it('resolves in-wall, overhead, and vertical vent elevations', () => {
    const wall = run('cold_water', { elevationMode: 'in_wall' });
    const overhead = run('hot_water', { system: 'hot_water', elevationMode: 'overhead' });
    const vent = run('vent', { elevationMode: 'vertical' });

    expect(resolvePlumbingRunPath({ system: plumbingSystemWithRun(wall), run: wall }).points[0]!.y)
      .toBeCloseTo(defaultPlumbingElevationDefaults.waterInWallHeightM);
    expect(resolvePlumbingRunPath({ system: plumbingSystemWithRun(overhead), run: overhead }).points[0]!.y)
      .toBeCloseTo(defaultPlumbingElevationDefaults.ceilingElevationM - defaultPlumbingElevationDefaults.waterOverheadDropM);
    expect(resolvePlumbingRunPath({ system: plumbingSystemWithRun(vent), run: vent }).points[1]!.y)
      .toBeGreaterThan(defaultPlumbingElevationDefaults.roofElevationM);
  });

  it('builds scene-backed pipe, fitting, and fixture groups from model counts', () => {
    const withToilet = addFixtureToPlumbingSystem({
      system: createDefaultPlumbingSystem(),
      fixtureType: 'toilet',
      position: { x: 0, y: 0, z: 0 },
      idSeed: 'wc',
    });
    const withLav = addFixtureToPlumbingSystem({
      system: withToilet,
      fixtureType: 'lavatory',
      position: { x: 2, y: 0, z: 0 },
      idSeed: 'lav',
    });
    const startNodeId = withLav.fixtures[0]!.connectionNodeIds.sanitary![0]!;
    const endNodeId = withLav.fixtures[1]!.connectionNodeIds.sanitary![0]!;
    const system = addRunToPlumbingSystem({
      system: withLav,
      systemType: 'sanitary',
      startNodeId,
      endNodeId,
      routePoints: [{ x: 1, y: 0, z: 1 }],
      diameterInches: 3,
      slopeInPerFt: 0.25,
      idSeed: 'ss',
    });

    const scene = buildDesignBuilderViewerPlumbingScene({
      plumbingSystem: system,
      visibility: { showLabels: false },
    });

    expect(scene.group.name).toBe('PlumbingSystem3D');
    expect(scene.group.children.filter((child) => child.name.startsWith('plumbing_run:'))).toHaveLength(system.runs.length);
    expect(scene.group.children.filter((child) => child.name.startsWith('plumbing_fitting:'))).toHaveLength(system.fittings.length);
    expect(scene.group.children.filter((child) => child.name.startsWith('plumbing_fixture:'))).toHaveLength(system.fixtures.length);
  });

  it('creates required procedural fixture parts', () => {
    const materials = createPlumbingThreeMaterials();
    const fixtureSystem = addFixtureToPlumbingSystem({
      system: createDefaultPlumbingSystem(),
      fixtureType: 'toilet',
      position: { x: 0, y: 0, z: 0 },
      idSeed: 'wc-parts',
    });
    const lavSystem = addFixtureToPlumbingSystem({
      system: createDefaultPlumbingSystem(),
      fixtureType: 'lavatory',
      position: { x: 0, y: 0, z: 0 },
      idSeed: 'lav-parts',
    });
    const drainSystem = addFixtureToPlumbingSystem({
      system: createDefaultPlumbingSystem(),
      fixtureType: 'floor_drain',
      position: { x: 0, y: 0, z: 0 },
      idSeed: 'fd-parts',
    });
    const heaterSystem = addFixtureToPlumbingSystem({
      system: createDefaultPlumbingSystem(),
      fixtureType: 'water_heater',
      position: { x: 0, y: 0, z: 0 },
      idSeed: 'wh-parts',
    });

    const wcNames = groupObjectNames(createProceduralPlumbingFixtureMesh({
      fixture: fixtureSystem.fixtures[0]!,
      position: { x: 0, y: 0, z: 0 },
      materials,
    }).group);
    expect(Array.from(wcNames)).toEqual(expect.arrayContaining(['WC base block', 'WC bowl', 'WC rear tank']));
    expect(Array.from(groupObjectNames(createProceduralPlumbingFixtureMesh({
      fixture: lavSystem.fixtures[0]!,
      position: { x: 0, y: 0, z: 0 },
      materials,
    }).group))).toEqual(expect.arrayContaining(['lavatory counter', 'lavatory basin depression']));
    expect(groupObjectNames(createProceduralPlumbingFixtureMesh({
      fixture: drainSystem.fixtures[0]!,
      position: { x: 0, y: 0, z: 0 },
      materials,
    }).group).has('floor drain disk')).toBe(true);
    expect(groupObjectNames(createProceduralPlumbingFixtureMesh({
      fixture: heaterSystem.fixtures[0]!,
      position: { x: 0, y: 0, z: 0 },
      materials,
    }).group).has('water heater cylinder body')).toBe(true);
  });

  it('aligns floor-mounted fixture mesh bottoms to the finished floor instead of the pipe elevation', () => {
    const materials = createPlumbingThreeMaterials();
    const fixtureSystem = addFixtureToPlumbingSystem({
      system: createDefaultPlumbingSystem(),
      fixtureType: 'toilet',
      position: { x: 1.25, y: -0.35, z: 2.5 },
      idSeed: 'wc-floor-align',
    });
    const finishedFloorY = 0.125;
    const group = createProceduralPlumbingFixtureMesh({
      fixture: fixtureSystem.fixtures[0]!,
      position: { x: 1.25, y: -0.35, z: 2.5 },
      finishedFloorY,
      baseClearanceM: 0,
      materials,
    }).group;
    const bounds = objectBounds(group);

    expect(bounds.min.y).toBeCloseTo(finishedFloorY, 6);
    expect(group.position.x).toBeCloseTo(1.25);
    expect(group.position.z).toBeCloseTo(2.5);
    expect(group.userData.fixtureBaseAlignment).toMatchObject({
      targetBaseY: finishedFloorY,
      afterMinY: finishedFloorY,
    });
  });

  it('keeps fixture body placement separate from resolved sanitary riser depth in the scene', () => {
    const withFixture = addFixtureToPlumbingSystem({
      system: createDefaultPlumbingSystem(),
      fixtureType: 'toilet',
      position: { x: 0, y: 0, z: 0 },
      idSeed: 'wc-scene-floor',
    });
    const mainNodes: PlumbingNode[] = [
      { id: 'main-a', kind: 'building_drain_exit', system: 'sanitary', position: { x: -2, y: -0.4, z: 0.12 }, label: 'A' },
      { id: 'main-b', kind: 'building_drain_exit', system: 'sanitary', position: { x: 2, y: -0.4, z: 0.12 }, label: 'B' },
    ];
    const mainRun = run('sanitary', {
      id: 'floor-align-main-run',
      startNodeId: 'main-a',
      endNodeId: 'main-b',
      path: [mainNodes[0]!.position, mainNodes[1]!.position],
    });
    const result = createOrReplaceFixtureRoughInAssembly({
      system: { ...withFixture, nodes: [...withFixture.nodes, ...mainNodes], runs: [mainRun] },
      fixtureId: withFixture.fixtures[0]!.id,
      mainRunId: mainRun.id,
      tapPoint: { x: 0, y: -0.4, z: 0.12 },
      segmentIndex: 1,
    });
    const finishedFloorY = 0.15;
    const scene = buildDesignBuilderViewerPlumbingScene({
      plumbingSystem: result.system,
      visibility: { showLabels: false },
      elevationDefaults: {
        slabTopElevationM: finishedFloorY,
        slabThicknessM: finishedFloorY,
      },
    });
    const fixtureGroup = scene.group.children.find((child) => child.name.startsWith('plumbing_fixture:'))!;
    const riserGroup = scene.group.children.find((child) => child.name.startsWith('plumbing_rough_in:'))!;
    const fixtureBounds = objectBounds(fixtureGroup);
    const riserBounds = objectBounds(riserGroup);

    expect(fixtureBounds.min.y).toBeCloseTo(finishedFloorY + 0.01, 6);
    expect(riserBounds.min.y).toBeLessThan(finishedFloorY);
    expect(riserBounds.max.y).toBeGreaterThanOrEqual(finishedFloorY);
  });

  it('places arbitrary object bases by bounding box bottom', () => {
    const group = new THREE.Group();
    group.position.set(0, -2, 0);
    group.add(new THREE.Mesh(
      new THREE.BoxGeometry(0.4, 0.8, 0.4),
      new THREE.MeshBasicMaterial(),
    ));
    group.children[0]!.position.y = 0.4;

    const alignment = placeObjectBaseAtY(group, 0.25, 0.02);

    expect(alignment?.beforeMinY).toBeCloseTo(-2, 6);
    expect(alignment?.afterMinY).toBeCloseTo(0.27, 6);
    expect(objectBounds(group).min.y).toBeCloseTo(0.27, 6);
  });

  it('aligns distribution boxes by pipe connector centerline instead of floor elevation', () => {
    const materials = createPlumbingThreeMaterials();
    const equipment = {
      id: 'd-box-equipment',
      equipmentType: 'distribution_box' as const,
      label: 'D-Box',
      position: { x: 0, y: 0.5, z: 0 },
      rotationRadians: 0,
      connectionNodeIds: ['d-box-node'],
    };
    const equipmentGroup = createProceduralPlumbingEquipmentMesh({
      equipment,
      position: equipment.position,
      elevationDefaults: defaultPlumbingElevationDefaults,
      materials,
    });
    const port = (equipmentGroup.userData.ports as ConnectorPort[]).find((candidate) => candidate.id === 'pipe_centerline')!;
    const target = new THREE.Vector3(2, -0.72, 1);
    const alignment = alignObjectPortToWorldPoint(equipmentGroup, port, target);
    const finalPort = port.localPosition.clone().applyMatrix4(equipmentGroup.matrixWorld);

    expect(equipmentGroup.userData.placementMode).toBe('buried-port-aligned');
    expect((equipmentGroup.userData.ports as ConnectorPort[]).map((candidate) => candidate.id))
      .toEqual(expect.arrayContaining(['pipe_centerline', 'inlet', 'outlet']));
    expect(alignment?.after.toArray()).toEqual(finalPort.toArray());
    expect(finalPort.x).toBeCloseTo(target.x, 6);
    expect(finalPort.y).toBeCloseTo(target.y, 6);
    expect(finalPort.z).toBeCloseTo(target.z, 6);
  });

  it('places D-box scene geometry on the resolved sloped pipe endpoint and lets pipes penetrate the box', () => {
    const dBoxNode: PlumbingNode = {
      id: 'd-box-node',
      kind: 'distribution_box',
      system: 'sanitary',
      position: { x: 2, y: -0.72, z: 0 },
      equipmentId: 'd-box-equipment',
      label: 'Distribution box',
    };
    const sourceNode: PlumbingNode = {
      id: 'source-node',
      kind: 'building_drain_exit',
      system: 'sanitary',
      position: { x: 0, y: -0.6, z: 0 },
      label: 'BD',
    };
    const dBoxRun = run('sanitary', {
      id: 'to-d-box',
      startNodeId: sourceNode.id,
      endNodeId: dBoxNode.id,
      path: [sourceNode.position, dBoxNode.position],
      elevationMode: 'user_defined',
      diameterInches: 4,
      slopeInPerFt: 0.125,
    });
    const system: PlumbingSystem = {
      ...createDefaultPlumbingSystem(),
      nodes: [sourceNode, dBoxNode],
      runs: [dBoxRun],
      equipment: [{
        id: 'd-box-equipment',
        equipmentType: 'distribution_box',
        label: 'D-Box',
        position: { x: dBoxNode.position.x, y: 0, z: dBoxNode.position.z },
        rotationRadians: 0,
        connectionNodeIds: [dBoxNode.id],
      }],
    };
    const scene = buildDesignBuilderViewerPlumbingScene({
      plumbingSystem: system,
      visibility: { showLabels: false },
      elevationDefaults: {
        slabTopElevationM: 0.15,
        slabThicknessM: 0.15,
      },
    });
    const dBoxGroup = scene.group.children.find((child) => child.name === 'plumbing_equipment:d-box-equipment')!;
    const pipeGroup = scene.group.children.find((child) => child.name === 'plumbing_run:to-d-box')!;
    const port = (dBoxGroup.userData.ports as ConnectorPort[]).find((candidate) => candidate.id === 'pipe_centerline')!;
    const finalPort = port.localPosition.clone().applyMatrix4(dBoxGroup.matrixWorld);
    const pipe = meshByName(pipeGroup, 'pipe segment 1');
    const pipeEndpoints = cylinderEndpoints(pipe).sort((a, b) => a.x - b.x);

    expect(finalPort.y).toBeCloseTo(dBoxNode.position.y, 6);
    expect(dBoxGroup.position.y).not.toBeCloseTo(0.15, 6);
    expect(dBoxGroup.userData.portAlignment.target[1]).toBeCloseTo(dBoxNode.position.y, 6);
    expect(pipeEndpoints[1]!.x).toBeGreaterThan(dBoxNode.position.x);
  });

  it('creates required procedural fitting parts', () => {
    const materials = createPlumbingThreeMaterials();
    const coupling = createProceduralPlumbingFittingMesh({
      fitting: fitting('coupling'),
      position: { x: 0, y: 0, z: 0 },
      materials,
    }).group;
    expect(groupObjectNames(coupling).has('coupling sleeve')).toBe(true);
    expect(groupHasSphereGeometry(coupling)).toBe(false);

    const elbow90 = createProceduralPlumbingFittingMesh({
      fitting: fitting('elbow_90_long_sweep'),
      position: { x: 0, y: 0, z: 0 },
      materials,
    }).group;
    expect(Array.from(groupObjectNames(elbow90))).toEqual(expect.arrayContaining(['long sweep elbow inlet sleeve', 'long sweep elbow outlet sleeve']));
    expect(groupHasSphereGeometry(elbow90)).toBe(false);

    const elbow45 = createProceduralPlumbingFittingMesh({
      fitting: fitting('elbow_45'),
      position: { x: 0, y: 0, z: 0 },
      materials,
    }).group;
    expect(groupObjectNames(elbow45).has('elbow miter body')).toBe(true);
    expect(groupHasSphereGeometry(elbow45)).toBe(false);

    expect(Array.from(groupObjectNames(createProceduralPlumbingFittingMesh({
      fitting: fitting('tee'),
      position: { x: 0, y: 0, z: 0 },
      materials,
    }).group))).toEqual(expect.arrayContaining(['tee main sleeve', 'tee branch sleeve']));
    expect(groupObjectNames(createProceduralPlumbingFittingMesh({
      fitting: fitting('wye'),
      position: { x: 0, y: 0, z: 0 },
      materials,
    }).group).has('wye angled branch sleeve')).toBe(true);
    const reducedWye = createProceduralPlumbingFittingMesh({
      fitting: fitting('wye', { diameterInches: 3, secondaryDiameterInches: 1.5 }),
      position: { x: 0, y: 0, z: 0 },
      materials,
    }).group;
    const reducedWyeMain = meshByName(reducedWye, 'wye main sleeve');
    const reducedWyeBranch = meshByName(reducedWye, 'wye angled branch sleeve');
    expect((reducedWyeBranch.geometry as THREE.CylinderGeometry).parameters.radiusTop)
      .toBeLessThan((reducedWyeMain.geometry as THREE.CylinderGeometry).parameters.radiusTop);
    expect(groupObjectNames(createProceduralPlumbingFittingMesh({
      fitting: fitting('cap'),
      position: { x: 0, y: 0, z: 0 },
      materials,
    }).group).has('cap end disk')).toBe(true);
    expect(groupObjectNames(createProceduralPlumbingFittingMesh({
      fitting: fitting('cleanout_adapter'),
      position: { x: 0, y: 0, z: 0 },
      materials,
    }).group).has('cleanout raised cap')).toBe(true);
    expect(Array.from(groupObjectNames(createProceduralPlumbingFittingMesh({
      fitting: fitting('ball_valve', { system: 'cold_water', material: 'pex', schedule: 'N/A', diameterInches: 0.5 }),
      position: { x: 0, y: 0, z: 0 },
      materials,
    }).group))).toEqual(expect.arrayContaining(['valve body', 'valve handle']));
    const selected = createProceduralPlumbingFittingMesh({
      fitting: fitting('coupling'),
      position: { x: 0, y: 0, z: 0 },
      materials,
      selected: true,
    }).group;
    expect(groupObjectNames(selected).has('fitting selection ring')).toBe(true);
    expect(groupHasSphereGeometry(selected)).toBe(false);
  });

  it('fits coupling sleeves on the resolved centerline and trims pipe meshes into the socket', () => {
    const sanitary = run('sanitary', {
      path: [
        { x: 0, y: 0, z: 0 },
        { x: 2, y: 0, z: 0 },
        { x: 4, y: 0, z: 0 },
      ],
    });
    const system: PlumbingSystem = {
      ...createDefaultPlumbingSystem(),
      nodes: [
        { id: 'node-a', kind: 'fixture_connection', system: 'sanitary', position: { x: 0, y: 0, z: 0 }, label: 'A' },
        { id: 'node-b', kind: 'fixture_connection', system: 'sanitary', position: { x: 4, y: 0, z: 0 }, label: 'B' },
        { id: 'node-c', kind: 'fitting', system: 'sanitary', position: { x: 2, y: 0, z: 0 }, label: 'CPLG' },
      ],
      runs: [sanitary],
      fittings: [fitting('coupling', { nodeId: 'node-c', connectedRunIds: [sanitary.id] })],
    };
    const resolved = resolvePlumbingRunPath({ system, run: sanitary });
    const fittingPosition = resolved.points[1]!;
    const fittingGroup = createProceduralPlumbingFittingMesh({
      fitting: system.fittings[0]!,
      position: fittingPosition,
      materials: createPlumbingThreeMaterials(),
      runs: system.runs,
      nodes: system.nodes,
      resolvedRunPaths: [resolved],
    }).group;
    const sleeve = meshByName(fittingGroup, 'coupling sleeve');
    const couplingDirection = new THREE.Vector3(
      resolved.points[0]!.x - resolved.points[1]!.x,
      resolved.points[0]!.y - resolved.points[1]!.y,
      resolved.points[0]!.z - resolved.points[1]!.z,
    ).normalize();

    expect(fittingGroup.position.toArray()).toEqual([fittingPosition.x, fittingPosition.y, fittingPosition.z]);
    expect(Math.abs(cylinderAxis(sleeve).dot(couplingDirection))).toBeCloseTo(1, 5);

    const originalPath = sanitary.path.map((point) => ({ ...point }));
    const pipeGroup = createPipeTubeMesh({
      run: sanitary,
      resolvedPath: resolved,
      materials: createPlumbingThreeMaterials(),
      fittingCenters: [new THREE.Vector3(fittingPosition.x, fittingPosition.y, fittingPosition.z)],
    });
    const firstSegment = meshByName(pipeGroup, 'pipe segment 1');
    const secondSegment = meshByName(pipeGroup, 'pipe segment 2');
    const firstEndpoints = cylinderEndpoints(firstSegment).sort((a, b) => a.x - b.x);
    const secondEndpoints = cylinderEndpoints(secondSegment).sort((a, b) => a.x - b.x);
    const socketLength = fittingSocketLengthMeters(sanitary.diameterInches);

    expect(firstEndpoints[1]!.x).toBeCloseTo(2 - socketLength, 4);
    expect(secondEndpoints[0]!.x).toBeCloseTo(2 + socketLength, 4);
    expect(sanitary.path).toEqual(originalPath);
  });

  it('fits elbow, tee, and wye sockets to connected resolved run directions', () => {
    const materials = createPlumbingThreeMaterials();
    const elbowRun = run('sanitary', {
      path: [
        { x: 0, y: 0, z: 0 },
        { x: 1, y: 0, z: 0 },
        { x: 1, y: 0, z: 1 },
      ],
    });
    const elbowSystem: PlumbingSystem = {
      ...createDefaultPlumbingSystem(),
      nodes: [
        { id: 'node-a', kind: 'fixture_connection', system: 'sanitary', position: { x: 0, y: 0, z: 0 }, label: 'A' },
        { id: 'node-b', kind: 'fixture_connection', system: 'sanitary', position: { x: 1, y: 0, z: 1 }, label: 'B' },
        { id: 'bend-node', kind: 'fitting', system: 'sanitary', position: { x: 1, y: 0, z: 0 }, label: '90' },
      ],
      runs: [elbowRun],
      fittings: [fitting('elbow_90', { nodeId: 'bend-node', connectedRunIds: [elbowRun.id] })],
    };
    const elbowResolved = resolvePlumbingRunPath({ system: elbowSystem, run: elbowRun });
    const elbow = createProceduralPlumbingFittingMesh({
      fitting: elbowSystem.fittings[0]!,
      position: elbowResolved.points[1]!,
      materials,
      runs: elbowSystem.runs,
      nodes: elbowSystem.nodes,
      resolvedRunPaths: [elbowResolved],
    }).group;
    expect(elbow.position.y).toBeCloseTo(elbowResolved.points[1]!.y);
    const elbowIn = new THREE.Vector3(
      elbowResolved.points[0]!.x - elbowResolved.points[1]!.x,
      elbowResolved.points[0]!.y - elbowResolved.points[1]!.y,
      elbowResolved.points[0]!.z - elbowResolved.points[1]!.z,
    ).normalize();
    const elbowOut = new THREE.Vector3(
      elbowResolved.points[2]!.x - elbowResolved.points[1]!.x,
      elbowResolved.points[2]!.y - elbowResolved.points[1]!.y,
      elbowResolved.points[2]!.z - elbowResolved.points[1]!.z,
    ).normalize();
    expect(Math.abs(cylinderAxis(meshByName(elbow, 'elbow inlet sleeve')).dot(elbowIn))).toBeCloseTo(1, 5);
    expect(Math.abs(cylinderAxis(meshByName(elbow, 'elbow outlet sleeve')).dot(elbowOut))).toBeCloseTo(1, 5);

    const teeNodes: PlumbingNode[] = [
      { id: 'tap', kind: 'fitting', system: 'sanitary', position: { x: 0, y: 0, z: 0 }, label: 'TEE' },
      { id: 'west', kind: 'fixture_connection', system: 'sanitary', position: { x: -1, y: 0, z: 0 }, label: 'W' },
      { id: 'east', kind: 'fixture_connection', system: 'sanitary', position: { x: 1, y: 0, z: 0 }, label: 'E' },
      { id: 'north', kind: 'fixture_connection', system: 'sanitary', position: { x: 0, y: 0, z: 1 }, label: 'N' },
    ];
    const teeRuns = [
      run('sanitary', { id: 'west-run', startNodeId: 'west', endNodeId: 'tap', path: [teeNodes[1]!.position, teeNodes[0]!.position] }),
      run('sanitary', { id: 'east-run', startNodeId: 'tap', endNodeId: 'east', path: [teeNodes[0]!.position, teeNodes[2]!.position] }),
      run('sanitary', { id: 'branch-run', startNodeId: 'tap', endNodeId: 'north', path: [teeNodes[0]!.position, teeNodes[3]!.position] }),
    ];
    const teeSystem = {
      ...createDefaultPlumbingSystem(),
      nodes: teeNodes,
      runs: teeRuns,
      fittings: [fitting('tee', { nodeId: 'tap', connectedRunIds: teeRuns.map((item) => item.id) })],
    };
    const teePaths = teeRuns.map((item) => resolvePlumbingRunPath({ system: teeSystem, run: item }));
    const tee = createProceduralPlumbingFittingMesh({
      fitting: teeSystem.fittings[0]!,
      position: teePaths[0]!.points[1]!,
      materials,
      runs: teeRuns,
      nodes: teeNodes,
      resolvedRunPaths: teePaths,
    }).group;
    expect(Math.abs(cylinderAxis(meshByName(tee, 'tee main sleeve')).dot(new THREE.Vector3(1, 0, 0)))).toBeGreaterThan(0.999);
    expect(Math.abs(cylinderAxis(meshByName(tee, 'tee branch sleeve')).dot(new THREE.Vector3(0, 0, 1)))).toBeGreaterThan(0.999);

    const wyeNodes = [
      ...teeNodes.slice(0, 3),
      { id: 'diag', kind: 'fixture_connection', system: 'sanitary' as const, position: { x: 1, y: 0, z: 1 }, label: 'D' },
    ];
    const wyeRuns = [
      teeRuns[0]!,
      teeRuns[1]!,
      run('sanitary', { id: 'diag-run', startNodeId: 'tap', endNodeId: 'diag', path: [wyeNodes[0]!.position, wyeNodes[3]!.position] }),
    ];
    const wyeSystem = {
      ...createDefaultPlumbingSystem(),
      nodes: wyeNodes,
      runs: wyeRuns,
      fittings: [fitting('wye', { nodeId: 'tap', connectedRunIds: wyeRuns.map((item) => item.id) })],
    };
    const wyePaths = wyeRuns.map((item) => resolvePlumbingRunPath({ system: wyeSystem, run: item }));
    const wye = createProceduralPlumbingFittingMesh({
      fitting: wyeSystem.fittings[0]!,
      position: wyePaths[0]!.points[1]!,
      materials,
      runs: wyeRuns,
      nodes: wyeNodes,
      resolvedRunPaths: wyePaths,
    }).group;
    expect(Math.abs(cylinderAxis(meshByName(wye, 'wye angled branch sleeve')).dot(new THREE.Vector3(1, 0, 1).normalize()))).toBeGreaterThan(0.999);
  });

  it('exposes resolved centerline helpers and dev centerline geometry', () => {
    const sanitary = run('sanitary');
    const system = plumbingSystemWithRun(sanitary);
    const resolved = resolvePlumbingRunPath({ system, run: sanitary });
    const directions = getConnectedRunDirectionsAtNode('node-a', [sanitary], [resolved]);
    expect(directions).toHaveLength(1);
    expect(directions[0]!.center?.toArray()).toEqual([
      resolved.points[0]!.x,
      resolved.points[0]!.y,
      resolved.points[0]!.z,
    ]);

    const pipeGroup = createPipeTubeMesh({
      run: sanitary,
      resolvedPath: resolved,
      materials: createPlumbingThreeMaterials(),
      showCenterline: true,
    });
    expect(lineByName(pipeGroup, 'plumbing run centerline')).toBeTruthy();
  });

  it('renders invalid and auto-generated bend fittings without sphere markers', () => {
    const materials = createPlumbingThreeMaterials();
    const invalid = createProceduralPlumbingFittingMesh({
      fitting: fitting('manifold'),
      position: { x: 0, y: 0, z: 0 },
      materials,
    });
    expect(groupObjectNames(invalid.group).has('pipe sleeve transparent barrel')).toBe(true);
    expect(groupHasSphereGeometry(invalid.group)).toBe(false);
    expect(invalid.validationIssues.map((issue) => issue.code)).toContain('fitting_type_missing_procedural_renderer');

    const withLav = addFixtureToPlumbingSystem({
      system: createDefaultPlumbingSystem(),
      fixtureType: 'lavatory',
      position: { x: 0, y: 0, z: 0 },
      idSeed: 'bend-lav',
    });
    const withSink = addFixtureToPlumbingSystem({
      system: withLav,
      fixtureType: 'kitchen_sink',
      position: { x: 2, y: 0, z: 2 },
      idSeed: 'bend-sink',
    });
    const system = addRunToPlumbingSystem({
      system: withSink,
      systemType: 'sanitary',
      startNodeId: withSink.fixtures[0]!.connectionNodeIds.sanitary![0]!,
      endNodeId: withSink.fixtures[1]!.connectionNodeIds.sanitary![0]!,
      routePoints: [{ x: 2, y: 0, z: 0 }],
      diameterInches: 3,
      material: 'pvc',
      slopeInPerFt: 0.25,
    });
    const elbow = system.fittings.find((item) => item.type === 'elbow_90_long_sweep');
    expect(elbow).toBeTruthy();
    const mesh = createProceduralPlumbingFittingMesh({
      fitting: elbow!,
      position: { x: 2, y: -0.4, z: 0 },
      materials,
      runs: system.runs,
      nodes: system.nodes,
    }).group;
    expect(groupObjectNames(mesh).has('long sweep elbow inlet sleeve')).toBe(true);
    expect(groupHasSphereGeometry(mesh)).toBe(false);
  });

  it('stores model-backed userData and resolves selected 3D plumbing back to the model object', () => {
    const materials = createPlumbingThreeMaterials();
    const fittingModel = fitting('coupling');
    const group = createProceduralPlumbingFittingMesh({
      fitting: fittingModel,
      position: { x: 0, y: 0, z: 0 },
      materials,
    }).group;
    const child = group.children[0]!;
    const pickData = resolveSelectableDataForObject(child);

    expect(group.userData).toMatchObject({
      objectType: 'plumbing_fitting',
      objectId: fittingModel.id,
    });
    expect(pickData?.plumbingSelection).toEqual({ kind: 'fitting', id: fittingModel.id });
  });

  it('renders rough-in risers as selectable vertical pipe meshes', () => {
    const withFixture = addFixtureToPlumbingSystem({
      system: createDefaultPlumbingSystem(),
      fixtureType: 'toilet',
      position: { x: 0, y: 0, z: 0 },
      idSeed: 'rough-wc',
    });
    const mainNodes: PlumbingNode[] = [
      { id: 'main-a', kind: 'building_drain_exit', system: 'sanitary', position: { x: -2, y: -0.4, z: 0.12 }, label: 'A' },
      { id: 'main-b', kind: 'building_drain_exit', system: 'sanitary', position: { x: 2, y: -0.4, z: 0.12 }, label: 'B' },
    ];
    const mainRun = run('sanitary', {
      id: 'main-run',
      startNodeId: 'main-a',
      endNodeId: 'main-b',
      path: [mainNodes[0]!.position, mainNodes[1]!.position],
    });
    const result = createOrReplaceFixtureRoughInAssembly({
      system: { ...withFixture, nodes: [...withFixture.nodes, ...mainNodes], runs: [mainRun] },
      fixtureId: withFixture.fixtures[0]!.id,
      mainRunId: mainRun.id,
      tapPoint: { x: 0, y: -0.4, z: 0.12 },
      segmentIndex: 1,
    });
    expect(result.roughIn).toBeTruthy();
    const riserRun = result.system.runs.find((item) => item.id === result.roughIn!.riserRunId)!;
    const resolved = resolvePlumbingRunPath({ system: result.system, run: riserRun });
    expect(resolved.points[0]!.y).toBeLessThan(0);
    expect(resolved.points[1]!.y).toBeCloseTo(0);
    const group = createPlumbingRiserMesh({
      roughIn: result.roughIn!,
      run: riserRun,
      resolvedPath: resolved,
      materials: createPlumbingThreeMaterials(),
    });
    expect(group.name).toBe(`plumbing_rough_in:${result.roughIn!.id}`);
    expect(groupObjectNames(group).has('riser pipe segment 1')).toBe(true);
    expect(resolveSelectableDataForObject(group.children[0]!)?.plumbingSelection).toEqual({
      kind: 'rough-in',
      id: result.roughIn!.id,
    });

    const scene = buildDesignBuilderViewerPlumbingScene({
      plumbingSystem: result.system,
      visibility: { showLabels: false },
    });
    expect(scene.group.children.filter((child) => child.name.startsWith('plumbing_rough_in:'))).toHaveLength(1);
    expect(scene.group.children.filter((child) => child.name === `plumbing_run:${riserRun.id}`)).toHaveLength(0);
  });

  it('renders WC sanitary rough-ins with a curved closet bend and trimmed riser/branch pipes', () => {
    const withFixture = addFixtureToPlumbingSystem({
      system: createDefaultPlumbingSystem(),
      fixtureType: 'toilet',
      position: { x: 0, y: 0, z: 0 },
      idSeed: 'closet-bend-wc',
    });
    const mainNodes: PlumbingNode[] = [
      { id: 'main-a', kind: 'building_drain_exit', system: 'sanitary', position: { x: -2, y: -0.4, z: 1 }, label: 'A' },
      { id: 'main-b', kind: 'building_drain_exit', system: 'sanitary', position: { x: 2, y: -0.4, z: 1 }, label: 'B' },
    ];
    const mainRun = run('sanitary', {
      id: 'closet-bend-main',
      startNodeId: 'main-a',
      endNodeId: 'main-b',
      path: [mainNodes[0]!.position, mainNodes[1]!.position],
    });
    const result = createOrReplaceFixtureRoughInAssembly({
      system: { ...withFixture, nodes: [...withFixture.nodes, ...mainNodes], runs: [mainRun] },
      fixtureId: withFixture.fixtures[0]!.id,
      mainRunId: mainRun.id,
      tapPoint: { x: 0, y: -0.4, z: 1 },
      segmentIndex: 1,
    });
    const roughIn = result.roughIn!;
    const bottomNode = result.system.nodes.find((node) => node.id === roughIn.riserBottomNodeId)!;
    const branchRun = result.system.runs.find((item) => item.id === roughIn.branchRunId)!;
    const scene = buildDesignBuilderViewerPlumbingScene({
      plumbingSystem: result.system,
      visibility: { showLabels: false },
    });
    const closetBend = scene.group.children.find((child) =>
      child.name.startsWith('plumbing_fitting:') &&
      child.userData.fittingType === 'closet_bend',
    )!;
    const riserGroup = scene.group.children.find((child) => child.name === `plumbing_rough_in:${roughIn.id}`)!;
    const branchGroup = scene.group.children.find((child) => child.name === `plumbing_run:${branchRun.id}`)!;
    const sweep = meshByName(closetBend, 'closet bend sweep body');
    const riser = meshByName(riserGroup, 'riser pipe segment 1');
    const branch = meshByName(branchGroup, 'pipe segment 1');
    const riserEndpoints = cylinderEndpoints(riser).sort((a, b) => a.y - b.y);
    const branchEndpoints = cylinderEndpoints(branch).sort((a, b) => a.distanceTo(new THREE.Vector3(bottomNode.position.x, bottomNode.position.y, bottomNode.position.z)) - b.distanceTo(new THREE.Vector3(bottomNode.position.x, bottomNode.position.y, bottomNode.position.z)));

    expect(sweep.geometry.type).toBe('TubeGeometry');
    expect(Array.from(groupObjectNames(closetBend))).toEqual(expect.arrayContaining([
      'closet bend sweep body',
      'closet bend riser socket',
      'closet bend drain socket',
    ]));
    expect(riserEndpoints[0]!.y).toBeGreaterThan(bottomNode.position.y);
    expect(branchEndpoints[0]!.distanceTo(new THREE.Vector3(bottomNode.position.x, bottomNode.position.y, bottomNode.position.z))).toBeGreaterThan(0.1);
    expect(result.system.fittings.some((fitting) => fitting.type === 'closet_bend' && roughIn.fittingIds.includes(fitting.id))).toBe(true);
  });

  it('resolves sanitary rough-in risers to the sloped fixture-to-septic branch invert', () => {
    const withFixture = addFixtureToPlumbingSystem({
      system: createDefaultPlumbingSystem(),
      fixtureType: 'toilet',
      position: { x: 0, y: 0, z: 0 },
      idSeed: 'septic-riser-wc',
    });
    const mainNodes: PlumbingNode[] = [
      { id: 'main-a', kind: 'building_drain_exit', system: 'sanitary', position: { x: -2, y: -0.4, z: 0 }, label: 'A' },
      { id: 'main-b', kind: 'building_drain_exit', system: 'sanitary', position: { x: 2, y: -0.4, z: 0 }, label: 'B' },
    ];
    const mainRun = run('sanitary', {
      id: 'main-to-septic',
      startNodeId: 'main-a',
      endNodeId: 'main-b',
      path: [mainNodes[0]!.position, mainNodes[1]!.position],
      slopeInPerFt: 0.125,
    });
    const withMain = { ...withFixture, nodes: [...withFixture.nodes, ...mainNodes], runs: [mainRun] };
    const tankResult = addCmuSepticTankToPlumbingSystem({
      system: withMain,
      centerX: 5.5,
      centerZ: 0,
      idSeed: 'septic-riser',
    });
    const septicInletId = tankResult.tank.connectionNodes.inletNodeId;
    const withSepticRun = addRunToPlumbingSystem({
      system: tankResult.system,
      systemType: 'sanitary',
      startNodeId: 'main-b',
      endNodeId: septicInletId,
      diameterInches: 3,
      slopeInPerFt: 0.125,
      idSeed: 'to-septic',
    });
    const result = createOrReplaceFixtureRoughInAssembly({
      system: withSepticRun,
      fixtureId: withFixture.fixtures[0]!.id,
      mainRunId: mainRun.id,
      tapPoint: { x: 0, y: -0.4, z: 0 },
      segmentIndex: 1,
    });

    const branchRun = result.system.runs.find((item) => item.id === result.roughIn!.branchRunId)!;
    const riserRun = result.system.runs.find((item) => item.id === result.roughIn!.riserRunId)!;
    const branchResolved = resolvePlumbingRunPath({ system: result.system, run: branchRun });
    const riserResolved = resolvePlumbingRunPath({ system: result.system, run: riserRun });

    expect(branchRun.startNodeId).toBe(result.roughIn!.riserBottomNodeId);
    expect(branchRun.endNodeId).toBe(result.roughIn!.tapNodeId);
    expect(riserResolved.points[0]!.y).toBeCloseTo(branchResolved.points[0]!.y, 6);
    expect(riserResolved.points[1]!.y).toBeGreaterThan(riserResolved.points[0]!.y);
  });

  it('warns for fitting types without a procedural renderer', () => {
    const sanitary = run('sanitary');
    const system = {
      ...plumbingSystemWithRun(sanitary),
      fittings: [fitting('manifold')],
    };

    expect(validatePlumbingSystem(system).map((item) => item.code))
      .toContain('fitting_type_missing_procedural_renderer');
  });

  it('registers the plumbing scene in the viewer scene registry', () => {
    const sanitary = run('sanitary');
    const scene = buildDesignBuilderViewerPlumbingScene({
      plumbingSystem: plumbingSystemWithRun(sanitary),
      visibility: { showLabels: false },
    });
    const root = new THREE.Group();
    const selectableObjects: THREE.Object3D[] = [];
    const registry = createDesignBuilderViewerSceneRegistry({
      root,
      selectableObjects,
      wallPickableObjects: [],
    });

    registry.addRootObject(scene.group);
    registry.registerSelectables(scene.selectableObjects);

    expect(root.children).toContain(scene.group);
    expect(selectableObjects).toHaveLength(scene.selectableObjects.length);
  });
});
