import * as THREE from 'three';
import { describe, expect, it } from 'vitest';
import {
  addFixtureToPlumbingSystem,
  addRunToPlumbingSystem,
  createDefaultPlumbingSystem,
  validatePlumbingSystem,
  type PlumbingFitting,
  type PlumbingNode,
  type PlumbingRun,
  type PlumbingSystem,
} from '../plumbing';
import { buildDesignBuilderViewerPlumbingScene } from '../plumbing/three/DesignBuilderViewerPlumbingScene';
import { createProceduralPlumbingFittingMesh } from '../plumbing/three/createProceduralPlumbingFittingMesh';
import { createProceduralPlumbingFixtureMesh } from '../plumbing/three/createProceduralPlumbingFixtureMesh';
import { createPlumbingThreeMaterials } from '../plumbing/three/plumbingThreeMaterials';
import {
  defaultPlumbingElevationDefaults,
  resolvePlumbingRunPath,
} from '../plumbing/three/plumbingElevationResolver';
import { groupObjectNames } from '../plumbing/three/plumbingThreeUtils';
import { resolveSelectableDataForObject } from '../ui/DesignBuilderViewerPicking';
import { createDesignBuilderViewerSceneRegistry } from '../ui/DesignBuilderViewerSceneRegistry';

function baseNodes(system: PlumbingRun['system']): PlumbingNode[] {
  return [
    {
      id: 'node-a',
      kind: 'fixture_connection',
      system,
      position: { x: 1, y: 0, z: 2 },
      label: 'A',
    },
    {
      id: 'node-b',
      kind: 'fixture_connection',
      system,
      position: { x: 4, y: 0, z: 2 },
      label: 'B',
    },
  ];
}

function run(system: PlumbingRun['system'], patch: Partial<PlumbingRun> = {}): PlumbingRun {
  return {
    id: `run-${system}`,
    system,
    startNodeId: 'node-a',
    endNodeId: 'node-b',
    path: [
      { x: 1, y: 0, z: 2 },
      { x: 2.5, y: 0, z: 3 },
      { x: 4, y: 0, z: 2 },
    ],
    diameterInches: system === 'sanitary' ? 3 : 0.5,
    material: system === 'sanitary' || system === 'vent' ? 'pvc' : 'pex',
    schedule: system === 'sanitary' || system === 'vent' ? 'SCH 40' : 'N/A',
    stockLengthFt: 10,
    stockLengthPreset: '10ft',
    stockLengthKind: 'stick',
    slopeInPerFt: system === 'sanitary' ? 0.25 : undefined,
    elevationMode: system === 'sanitary' ? 'under_slab' : 'in_wall',
    labelVisible: true,
    ...patch,
  };
}

function plumbingSystemWithRun(plumbingRun: PlumbingRun): PlumbingSystem {
  return {
    ...createDefaultPlumbingSystem(),
    nodes: baseNodes(plumbingRun.system),
    runs: [plumbingRun],
  };
}

function fitting(type: PlumbingFitting['type'], patch: Partial<PlumbingFitting> = {}): PlumbingFitting {
  return {
    id: `fitting-${type}`,
    type,
    system: 'sanitary',
    nodeId: 'node-a',
    connectedRunIds: ['run-sanitary'],
    diameterInches: 3,
    material: 'pvc',
    schedule: 'SCH 40',
    rotationRad: 0,
    elevationMode: 'under_slab',
    labelVisible: true,
    isAutoGenerated: false,
    ...patch,
  };
}

describe('Design Builder procedural plumbing 3D', () => {
  it('resolves 2D plan points to 3D X/Z and under-slab sanitary slope', () => {
    const sanitary = run('sanitary');
    const resolved = resolvePlumbingRunPath({
      system: plumbingSystemWithRun(sanitary),
      run: sanitary,
    });

    expect(resolved.points).toHaveLength(3);
    expect(resolved.points[0]).toMatchObject({ x: 1, z: 2 });
    expect(resolved.points[1]).toMatchObject({ x: 2.5, z: 3 });
    expect(resolved.points[0]!.y).toBeLessThan(defaultPlumbingElevationDefaults.slabTopElevationM);
    expect(resolved.points[2]!.y).toBeLessThan(resolved.points[0]!.y);
  });

  it('resolves in-wall, overhead, and vertical vent elevations', () => {
    const wall = run('cold_water', { elevationMode: 'in_wall' });
    const overhead = run('hot_water', { system: 'hot_water', elevationMode: 'overhead' });
    const vent = run('vent', { elevationMode: 'vertical' });

    expect(resolvePlumbingRunPath({ system: plumbingSystemWithRun(wall), run: wall }).points[0]!.y)
      .toBeCloseTo(defaultPlumbingElevationDefaults.waterInWallHeightM);
    expect(resolvePlumbingRunPath({ system: plumbingSystemWithRun(overhead), run: overhead }).points[0]!.y)
      .toBeCloseTo(defaultPlumbingElevationDefaults.ceilingElevationM - defaultPlumbingElevationDefaults.waterOverheadDropM);
    expect(resolvePlumbingRunPath({ system: plumbingSystemWithRun(vent), run: vent }).points[1]!.y)
      .toBeGreaterThan(defaultPlumbingElevationDefaults.roofElevationM);
  });

  it('builds scene-backed pipe, fitting, and fixture groups from model counts', () => {
    const withToilet = addFixtureToPlumbingSystem({
      system: createDefaultPlumbingSystem(),
      fixtureType: 'toilet',
      position: { x: 0, y: 0, z: 0 },
      idSeed: 'wc',
    });
    const withLav = addFixtureToPlumbingSystem({
      system: withToilet,
      fixtureType: 'lavatory',
      position: { x: 2, y: 0, z: 0 },
      idSeed: 'lav',
    });
    const startNodeId = withLav.fixtures[0]!.connectionNodeIds.sanitary![0]!;
    const endNodeId = withLav.fixtures[1]!.connectionNodeIds.sanitary![0]!;
    const system = addRunToPlumbingSystem({
      system: withLav,
      systemType: 'sanitary',
      startNodeId,
      endNodeId,
      routePoints: [{ x: 1, y: 0, z: 1 }],
      diameterInches: 3,
      slopeInPerFt: 0.25,
      idSeed: 'ss',
    });

    const scene = buildDesignBuilderViewerPlumbingScene({
      plumbingSystem: system,
      visibility: { showLabels: false },
    });

    expect(scene.group.name).toBe('PlumbingSystem3D');
    expect(scene.group.children.filter((child) => child.name.startsWith('plumbing_run:'))).toHaveLength(system.runs.length);
    expect(scene.group.children.filter((child) => child.name.startsWith('plumbing_fitting:'))).toHaveLength(system.fittings.length);
    expect(scene.group.children.filter((child) => child.name.startsWith('plumbing_fixture:'))).toHaveLength(system.fixtures.length);
  });

  it('creates required procedural fixture parts', () => {
    const materials = createPlumbingThreeMaterials();
    const fixtureSystem = addFixtureToPlumbingSystem({
      system: createDefaultPlumbingSystem(),
      fixtureType: 'toilet',
      position: { x: 0, y: 0, z: 0 },
      idSeed: 'wc-parts',
    });
    const lavSystem = addFixtureToPlumbingSystem({
      system: createDefaultPlumbingSystem(),
      fixtureType: 'lavatory',
      position: { x: 0, y: 0, z: 0 },
      idSeed: 'lav-parts',
    });
    const drainSystem = addFixtureToPlumbingSystem({
      system: createDefaultPlumbingSystem(),
      fixtureType: 'floor_drain',
      position: { x: 0, y: 0, z: 0 },
      idSeed: 'fd-parts',
    });
    const heaterSystem = addFixtureToPlumbingSystem({
      system: createDefaultPlumbingSystem(),
      fixtureType: 'water_heater',
      position: { x: 0, y: 0, z: 0 },
      idSeed: 'wh-parts',
    });

    const wcNames = groupObjectNames(createProceduralPlumbingFixtureMesh({
      fixture: fixtureSystem.fixtures[0]!,
      position: { x: 0, y: 0, z: 0 },
      materials,
    }).group);
    expect(Array.from(wcNames)).toEqual(expect.arrayContaining(['WC base block', 'WC bowl', 'WC rear tank']));
    expect(Array.from(groupObjectNames(createProceduralPlumbingFixtureMesh({
      fixture: lavSystem.fixtures[0]!,
      position: { x: 0, y: 0, z: 0 },
      materials,
    }).group))).toEqual(expect.arrayContaining(['lavatory counter', 'lavatory basin depression']));
    expect(groupObjectNames(createProceduralPlumbingFixtureMesh({
      fixture: drainSystem.fixtures[0]!,
      position: { x: 0, y: 0, z: 0 },
      materials,
    }).group).has('floor drain disk')).toBe(true);
    expect(groupObjectNames(createProceduralPlumbingFixtureMesh({
      fixture: heaterSystem.fixtures[0]!,
      position: { x: 0, y: 0, z: 0 },
      materials,
    }).group).has('water heater cylinder body')).toBe(true);
  });

  it('creates required procedural fitting parts', () => {
    const materials = createPlumbingThreeMaterials();
    expect(groupObjectNames(createProceduralPlumbingFittingMesh({
      fitting: fitting('coupling'),
      position: { x: 0, y: 0, z: 0 },
      materials,
    }).group).has('coupling sleeve')).toBe(true);
    expect(Array.from(groupObjectNames(createProceduralPlumbingFittingMesh({
      fitting: fitting('tee'),
      position: { x: 0, y: 0, z: 0 },
      materials,
    }).group))).toEqual(expect.arrayContaining(['tee main', 'tee branch']));
    expect(groupObjectNames(createProceduralPlumbingFittingMesh({
      fitting: fitting('wye'),
      position: { x: 0, y: 0, z: 0 },
      materials,
    }).group).has('wye branch')).toBe(true);
    expect(Array.from(groupObjectNames(createProceduralPlumbingFittingMesh({
      fitting: fitting('ball_valve', { system: 'cold_water', material: 'pex', schedule: 'N/A', diameterInches: 0.5 }),
      position: { x: 0, y: 0, z: 0 },
      materials,
    }).group))).toEqual(expect.arrayContaining(['valve body', 'valve handle']));
  });

  it('stores model-backed userData and resolves selected 3D plumbing back to the model object', () => {
    const materials = createPlumbingThreeMaterials();
    const fittingModel = fitting('coupling');
    const group = createProceduralPlumbingFittingMesh({
      fitting: fittingModel,
      position: { x: 0, y: 0, z: 0 },
      materials,
    }).group;
    const child = group.children[0]!;
    const pickData = resolveSelectableDataForObject(child);

    expect(group.userData).toMatchObject({
      objectType: 'plumbing_fitting',
      objectId: fittingModel.id,
    });
    expect(pickData?.plumbingSelection).toEqual({ kind: 'fitting', id: fittingModel.id });
  });

  it('warns for fitting types without a procedural renderer', () => {
    const sanitary = run('sanitary');
    const system = {
      ...plumbingSystemWithRun(sanitary),
      fittings: [fitting('manifold')],
    };

    expect(validatePlumbingSystem(system).map((item) => item.code))
      .toContain('fitting_type_missing_procedural_renderer');
  });

  it('registers the plumbing scene in the viewer scene registry', () => {
    const sanitary = run('sanitary');
    const scene = buildDesignBuilderViewerPlumbingScene({
      plumbingSystem: plumbingSystemWithRun(sanitary),
      visibility: { showLabels: false },
    });
    const root = new THREE.Group();
    const selectableObjects: THREE.Object3D[] = [];
    const registry = createDesignBuilderViewerSceneRegistry({
      root,
      selectableObjects,
      wallPickableObjects: [],
    });

    registry.addRootObject(scene.group);
    registry.registerSelectables(scene.selectableObjects);

    expect(root.children).toContain(scene.group);
    expect(selectableObjects).toHaveLength(scene.selectableObjects.length);
  });
});
